import { AgentType, AgentConfig, Department } from '@/types';

export const DEPARTMENTS: Department[] = [
  {
    id: 'research_strategy',
    name: 'Research & Strategy',
    description: 'Market intelligence, competitive analysis, and strategic planning',
    color: '#8B3CDE',
    agentCount: 6,
  },
  {
    id: 'content_growth',
    name: 'Content & Growth',
    description: 'Content creation, marketing, and audience engagement',
    color: '#F55477',
    agentCount: 6,
  },
  {
    id: 'sales_operations',
    name: 'Sales & Operations',
    description: 'Lead generation, customer relations, and performance analytics',
    color: '#000000',
    agentCount: 6,
  },
  {
    id: 'development_engineering',
    name: 'Development & Engineering',
    description: 'Software planning, code review, debugging, testing, documentation, deployment, security, database, and UI review',
    color: '#CA2851',
    agentCount: 9,
  },
];

export const PRIMARY_AGENT_IDS = [
  'market_research',
  'competitor_analysis',
  'audience_persona',
  'product_idea',
  'seo_keyword',
  'strategy_planner',
  'social_media_content',
  'copywriting',
  'ads_script',
  'email_marketing',
  'blog_seo_article',
  'visual_brief',
  'lead_finder',
  'lead_qualifier',
  'outreach_message',
  'crm_update',
  'customer_support',
  'analytics_report',
  'code-review-agent',
  'bug-fix-agent',
  'architecture-agent',
  'testing-agent',
  'documentation-agent',
  'deployment-agent',
  'security-review-agent',
  'database-agent',
  'ui-ux-review-agent',
] as const satisfies readonly AgentType[];

export const LEGACY_AGENT_IDS = [
  'offer_builder',
  'content_creator',
  'outreach',
  'report',
] as const satisfies readonly AgentType[];

export const AGENTS: Record<AgentType, AgentConfig> = {
  // Research & Strategy Department
  market_research: {
    id: 'market_research',
    name: 'Market Research Agent',
    role: 'Research & Strategy',
    description: 'Research market trends, analyze industry data, and generate insights about target markets.',
    icon: 'Search',
    color: '#8B3CDE',
    department: 'Research & Strategy',
    inputFields: [
      {
        name: 'market',
        label: 'Market',
        type: 'text',
        placeholder: 'e.g., SaaS, AI Tools, E-commerce',
        required: true,
      },
      {
        name: 'keywords',
        label: 'Keywords to Research',
        type: 'text',
        placeholder: 'Comma-separated keywords',
        required: true,
      },
      {
        name: 'scope',
        label: 'Research Scope',
        type: 'select',
        required: true,
        options: [
          { value: 'global', label: 'Global' },
          { value: 'regional', label: 'Regional' },
          { value: 'local', label: 'Local' },
        ],
      },
    ],
  },
  competitor_analysis: {
    id: 'competitor_analysis',
    name: 'Competitor Analysis Agent',
    role: 'Research & Strategy',
    description: 'Analyze competitor strategies, strengths, weaknesses, and market positioning.',
    icon: 'Target',
    color: '#8B3CDE',
    department: 'Research & Strategy',
    inputFields: [
      {
        name: 'competitors',
        label: 'Competitors (comma-separated)',
        type: 'text',
        placeholder: 'e.g., Company A, Company B, Company C',
        required: true,
      },
      {
        name: 'industry',
        label: 'Industry',
        type: 'text',
        placeholder: 'e.g., Digital Marketing, Cloud Storage',
        required: true,
      },
    ],
  },
  audience_persona: {
    id: 'audience_persona',
    name: 'Audience Persona Agent',
    role: 'Research & Strategy',
    description: 'Create detailed buyer personas and audience segments based on market research.',
    icon: 'Users',
    color: '#8B3CDE',
    department: 'Research & Strategy',
    inputFields: [
      {
        name: 'industry',
        label: 'Industry',
        type: 'text',
        placeholder: 'Target industry',
        required: true,
      },
      {
        name: 'product_type',
        label: 'Product/Service Type',
        type: 'text',
        placeholder: 'What type of product or service?',
        required: true,
      },
    ],
  },
  product_idea: {
    id: 'product_idea',
    name: 'Product Idea Agent',
    role: 'Research & Strategy',
    description: 'Generate innovative product concepts and validate market opportunities.',
    icon: 'Lightbulb',
    color: '#8B3CDE',
    department: 'Research & Strategy',
    inputFields: [
      {
        name: 'category',
        label: 'Category',
        type: 'text',
        placeholder: 'e.g., Mobile App, SaaS Platform, Hardware',
        required: true,
      },
      {
        name: 'target_market',
        label: 'Target Market',
        type: 'text',
        placeholder: 'Who is the target audience?',
        required: true,
      },
    ],
  },
  seo_keyword: {
    id: 'seo_keyword',
    name: 'SEO Keyword Agent',
    role: 'Research & Strategy',
    description: 'Discover high-value keywords and optimize content for search rankings.',
    icon: 'Search',
    color: '#8B3CDE',
    department: 'Research & Strategy',
    inputFields: [
      {
        name: 'topic',
        label: 'Topic',
        type: 'text',
        placeholder: 'Main topic or niche',
        required: true,
      },
      {
        name: 'difficulty',
        label: 'Competition Difficulty',
        type: 'select',
        required: true,
        options: [
          { value: 'low', label: 'Low' },
          { value: 'medium', label: 'Medium' },
          { value: 'high', label: 'High' },
        ],
      },
    ],
  },
  strategy_planner: {
    id: 'strategy_planner',
    name: 'Strategy Planner Agent',
    role: 'Research & Strategy',
    description: 'Develop comprehensive business strategies and execution roadmaps.',
    icon: 'BarChart3',
    color: '#8B3CDE',
    department: 'Research & Strategy',
    inputFields: [
      {
        name: 'objective',
        label: 'Primary Objective',
        type: 'text',
        placeholder: 'Main business goal',
        required: true,
      },
      {
        name: 'timeline',
        label: 'Timeline',
        type: 'select',
        required: true,
        options: [
          { value: '3_months', label: '3 Months' },
          { value: '6_months', label: '6 Months' },
          { value: '12_months', label: '12 Months' },
        ],
      },
    ],
  },

  // Content & Growth Department
  social_media_content: {
    id: 'social_media_content',
    name: 'Social Media Content Agent',
    role: 'Content & Growth',
    description: 'Generate engaging social media posts and platform-specific content strategies.',
    icon: 'Megaphone',
    color: '#F55477',
    department: 'Content & Growth',
    inputFields: [
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        required: true,
        options: [
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'twitter', label: 'Twitter/X' },
          { value: 'instagram', label: 'Instagram' },
          { value: 'facebook', label: 'Facebook' },
        ],
      },
      {
        name: 'topic',
        label: 'Topic',
        type: 'text',
        placeholder: 'Content topic or theme',
        required: true,
      },
    ],
  },
  copywriting: {
    id: 'copywriting',
    name: 'Copywriting Agent',
    role: 'Content & Growth',
    description: 'Create persuasive marketing copy for landing pages, ads, and promotional materials.',
    icon: 'FileText',
    color: '#F55477',
    department: 'Content & Growth',
    inputFields: [
      {
        name: 'content_type',
        label: 'Content Type',
        type: 'select',
        required: true,
        options: [
          { value: 'landing_page', label: 'Landing Page' },
          { value: 'ad_copy', label: 'Ad Copy' },
          { value: 'email_subject', label: 'Email Subject' },
        ],
      },
      {
        name: 'product',
        label: 'Product/Service',
        type: 'text',
        placeholder: 'What are you promoting?',
        required: true,
      },
    ],
  },
  ads_script: {
    id: 'ads_script',
    name: 'Ads Script Agent',
    role: 'Content & Growth',
    description: 'Write compelling advertising scripts for video, display, and paid campaigns.',
    icon: 'Megaphone',
    color: '#F55477',
    department: 'Content & Growth',
    inputFields: [
      {
        name: 'ad_type',
        label: 'Ad Type',
        type: 'select',
        required: true,
        options: [
          { value: 'video', label: 'Video Ad' },
          { value: 'display', label: 'Display Ad' },
          { value: 'social', label: 'Social Media Ad' },
        ],
      },
      {
        name: 'duration',
        label: 'Duration',
        type: 'select',
        required: true,
        options: [
          { value: '15s', label: '15 seconds' },
          { value: '30s', label: '30 seconds' },
          { value: '60s', label: '60 seconds' },
        ],
      },
    ],
  },
  email_marketing: {
    id: 'email_marketing',
    name: 'Email Marketing Agent',
    role: 'Content & Growth',
    description: 'Design and write effective email campaigns and nurture sequences.',
    icon: 'Mail',
    color: '#F55477',
    department: 'Content & Growth',
    inputFields: [
      {
        name: 'campaign_type',
        label: 'Campaign Type',
        type: 'select',
        required: true,
        options: [
          { value: 'newsletter', label: 'Newsletter' },
          { value: 'promotional', label: 'Promotional' },
          { value: 'nurture', label: 'Nurture Sequence' },
        ],
      },
      {
        name: 'audience',
        label: 'Target Audience',
        type: 'text',
        placeholder: 'Who is receiving this email?',
        required: true,
      },
    ],
  },
  blog_seo_article: {
    id: 'blog_seo_article',
    name: 'Blog SEO Article Agent',
    role: 'Content & Growth',
    description: 'Create SEO-optimized blog articles that rank and drive organic traffic.',
    icon: 'FileText',
    color: '#F55477',
    department: 'Content & Growth',
    inputFields: [
      {
        name: 'keyword',
        label: 'Primary Keyword',
        type: 'text',
        placeholder: 'Main SEO keyword',
        required: true,
      },
      {
        name: 'length',
        label: 'Article Length',
        type: 'select',
        required: true,
        options: [
          { value: '1000', label: '1000 words' },
          { value: '2000', label: '2000 words' },
          { value: '3000', label: '3000 words' },
        ],
      },
    ],
  },
  visual_brief: {
    id: 'visual_brief',
    name: 'Visual Brief Agent',
    role: 'Content & Growth',
    description: 'Generate detailed creative briefs for designers, illustrators, and visual content creators.',
    icon: 'Image',
    color: '#F55477',
    department: 'Content & Growth',
    inputFields: [
      {
        name: 'visual_type',
        label: 'Visual Type',
        type: 'select',
        required: true,
        options: [
          { value: 'infographic', label: 'Infographic' },
          { value: 'social_post', label: 'Social Media Post' },
          { value: 'presentation', label: 'Presentation' },
        ],
      },
      {
        name: 'brand_style',
        label: 'Brand Style',
        type: 'text',
        placeholder: 'Describe brand aesthetic',
        required: true,
      },
    ],
  },

  // Sales & Operations Department
  lead_finder: {
    id: 'lead_finder',
    name: 'Lead Finder Agent',
    role: 'Sales & Operations',
    description: 'Identify and qualify potential leads from various sources and databases.',
    icon: 'UserPlus',
    color: '#000000',
    department: 'Sales & Operations',
    inputFields: [
      {
        name: 'industry',
        label: 'Industry',
        type: 'text',
        placeholder: 'Target industry',
        required: true,
      },
      {
        name: 'company_size',
        label: 'Company Size',
        type: 'select',
        required: true,
        options: [
          { value: 'startup', label: 'Startup (1-50)' },
          { value: 'sme', label: 'SME (50-500)' },
          { value: 'enterprise', label: 'Enterprise (500+)' },
        ],
      },
    ],
  },
  lead_qualifier: {
    id: 'lead_qualifier',
    name: 'Lead Qualifier Agent',
    role: 'Sales & Operations',
    description: 'Score and qualify leads based on fit, interest, and buying signals.',
    icon: 'UserCheck',
    color: '#000000',
    department: 'Sales & Operations',
    inputFields: [
      {
        name: 'criteria',
        label: 'Qualification Criteria',
        type: 'select',
        required: true,
        options: [
          { value: 'basic', label: 'Basic (Budget + Authority)' },
          { value: 'advanced', label: 'Advanced (BANT + Timing)' },
        ],
      },
    ],
  },
  outreach_message: {
    id: 'outreach_message',
    name: 'Outreach Message Agent',
    role: 'Sales & Operations',
    description: 'Craft personalized outreach messages for cold emails and prospecting campaigns.',
    icon: 'MessageCircle',
    color: '#000000',
    department: 'Sales & Operations',
    inputFields: [
      {
        name: 'channel',
        label: 'Channel',
        type: 'select',
        required: true,
        options: [
          { value: 'email', label: 'Email' },
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'phone', label: 'Phone Script' },
        ],
      },
      {
        name: 'goal',
        label: 'Primary Goal',
        type: 'text',
        placeholder: 'e.g., Book meeting, Pricing review',
        required: true,
      },
    ],
  },
  crm_update: {
    id: 'crm_update',
    name: 'CRM Update Agent',
    role: 'Sales & Operations',
    description: 'Automatically update and maintain CRM records with latest customer interactions.',
    icon: 'Database',
    color: '#000000',
    department: 'Sales & Operations',
    inputFields: [
      {
        name: 'crm_system',
        label: 'CRM System',
        type: 'select',
        required: true,
        options: [
          { value: 'salesforce', label: 'Salesforce' },
          { value: 'hubspot', label: 'HubSpot' },
          { value: 'pipedrive', label: 'Pipedrive' },
        ],
      },
    ],
  },
  customer_support: {
    id: 'customer_support',
    name: 'Customer Support Agent',
    role: 'Sales & Operations',
    description: 'Handle customer inquiries, provide solutions, and maintain support documentation.',
    icon: 'Headphones',
    color: '#000000',
    department: 'Sales & Operations',
    inputFields: [
      {
        name: 'issue_type',
        label: 'Issue Type',
        type: 'select',
        required: true,
        options: [
          { value: 'technical', label: 'Technical Issue' },
          { value: 'quota', label: 'quota Question' },
          { value: 'general', label: 'General Inquiry' },
        ],
      },
    ],
  },
  analytics_report: {
    id: 'analytics_report',
    name: 'Analytics Report Agent',
    role: 'Sales & Operations',
    description: 'Generate comprehensive reports from sales data, metrics, and KPIs.',
    icon: 'PieChart',
    color: '#000000',
    department: 'Sales & Operations',
    inputFields: [
      {
        name: 'metric',
        label: 'Primary Metric',
        type: 'text',
        placeholder: 'e.g., Conversion Rate, Revenue, Churn',
        required: true,
      },
      {
        name: 'time_period',
        label: 'Time Period',
        type: 'select',
        required: true,
        options: [
          { value: 'weekly', label: 'Weekly' },
          { value: 'monthly', label: 'Monthly' },
          { value: 'quarterly', label: 'Quarterly' },
        ],
      },
    ],
  },

  // Development & Engineering Department
  'code-review-agent': {
    id: 'code-review-agent',
    name: 'Code Review Agent',
    role: 'Development & Engineering',
    description: 'Reviews code quality, structure, readability, maintainability, and potential bugs.',
    icon: 'Code',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },
  'bug-fix-agent': {
    id: 'bug-fix-agent',
    name: 'Bug Fix Agent',
    role: 'Development & Engineering',
    description: 'Analyzes errors, logs, screenshots, and failing behavior to propose a safe fix plan.',
    icon: 'Bug',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },
  'architecture-agent': {
    id: 'architecture-agent',
    name: 'Architecture Agent',
    role: 'Development & Engineering',
    description: 'Plans system architecture, project structure, data flow, and implementation phases.',
    icon: 'Workflow',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },
  'testing-agent': {
    id: 'testing-agent',
    name: 'Testing Agent',
    role: 'Development & Engineering',
    description: 'Creates testing checklists, QA plans, edge cases, and acceptance criteria.',
    icon: 'TestTube',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },
  'documentation-agent': {
    id: 'documentation-agent',
    name: 'Documentation Agent',
    role: 'Development & Engineering',
    description: 'Creates internal guides, user docs, technical reports, release notes, FAQs, and checklists.',
    icon: 'BookOpen',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },
  'deployment-agent': {
    id: 'deployment-agent',
    name: 'Deployment Agent',
    role: 'Development & Engineering',
    description: 'Prepares deployment plans, Vercel checks, environment checklists, smoke tests, and rollback notes.',
    icon: 'Rocket',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },
  'security-review-agent': {
    id: 'security-review-agent',
    name: 'Security Review Agent',
    role: 'Development & Engineering',
    description: 'Reviews security risks, secret exposure, RLS, file upload safety, and token handling.',
    icon: 'ShieldCheck',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },
  'database-agent': {
    id: 'database-agent',
    name: 'Database Agent',
    role: 'Development & Engineering',
    description: 'Plans and reviews Supabase schema, migrations, RLS, indexes, relationships, and storage policies.',
    icon: 'Database',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },
  'ui-ux-review-agent': {
    id: 'ui-ux-review-agent',
    name: 'UI/UX Review Agent',
    role: 'Development & Engineering',
    description: 'Reviews interface layout, readability, flows, accessibility, and responsive behavior.',
    icon: 'PanelsTopLeft',
    color: '#CA2851',
    department: 'Development & Engineering',
    inputFields: [],
  },

  // Legacy agents (kept for backward compatibility)
  offer_builder: {
    id: 'offer_builder',
    name: 'Offer Builder Agent',
    role: 'Content & Growth',
    description: 'Create compelling product or service offers based on market research and customer needs.',
    icon: 'Lightbulb',
    color: '#F55477',
    department: 'Content & Growth',
    inputFields: [],
  },
  content_creator: {
    id: 'content_creator',
    name: 'Content Creator Agent',
    role: 'Content & Growth',
    description: 'Generate high-quality marketing content, blog posts, and social media content.',
    icon: 'FileText',
    color: '#F55477',
    department: 'Content & Growth',
    inputFields: [],
  },
  outreach: {
    id: 'outreach',
    name: 'Outreach Agent',
    role: 'Sales & Operations',
    description: 'Generate personalized outreach messages and manage outreach campaigns.',
    icon: 'Send',
    color: '#000000',
    department: 'Sales & Operations',
    inputFields: [],
  },
  report: {
    id: 'report',
    name: 'Report Agent',
    role: 'Sales & Operations',
    description: 'Generate comprehensive reports from data, analysis, and insights.',
    icon: 'BarChart3',
    color: '#000000',
    department: 'Sales & Operations',
    inputFields: [],
  },
};
