import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#F1F7F7',
        foreground: '#5D6B6B',
        surface: '#D8E6E5',
        ink: '#5D6B6B',
        primary: '#F7CBCA',
        'primary-light': '#F7CBCA',
        'primary-dark': '#5D6B6B',
        secondary: '#BFDADB',
        'secondary-light': '#BFDADB',
        'secondary-dark': '#5D6B6B',
        accent: '#E6DDDA',
        'accent-light': '#E6DDDA',
        'accent-dark': '#5D6B6B',
        success: '#D8E6E5',
        'success-light': '#D8E6E5',
        'success-dark': '#5D6B6B',
        warning: '#F7CBCA',
        'warning-light': '#F7CBCA',
        'warning-dark': '#5D6B6B',
        error: '#F7CBCA',
        'error-light': '#F7CBCA',
        'error-dark': '#5D6B6B',
        'brand-rose': '#F7CBCA',
        'brand-ice': '#F1F7F7',
        'brand-teal': '#D8E6E5',
        'brand-sage': '#BFDADB',
        'brand-warm': '#E6DDDA',
        'brand-ink': '#5D6B6B',
      },
      backgroundColor: {
        'primary-subtle': '#F7CBCA',
        'secondary-subtle': '#BFDADB',
        'accent-subtle': '#E6DDDA',
      },
      borderColor: {
        'default': '#D8E6E5',
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'base': '0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px 0 rgb(0 0 0 / 0.04)',
        'md': '0 4px 6px -1px rgb(0 0 0 / 0.08), 0 2px 4px -1px rgb(0 0 0 / 0.04)',
        'lg': '0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -2px rgb(0 0 0 / 0.04)',
        'xl': '0 20px 25px -5px rgb(0 0 0 / 0.08), 0 10px 10px -5px rgb(0 0 0 / 0.04)',
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
        '3xl': '4rem',
      },
      borderRadius: {
        'none': '0px',
        'sm': '0.375rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
      },
      fontFamily: {
        'sans': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'mono': ['Fira Code', 'Menlo', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
    },
  },
  plugins: [],
}

export default config
