import { agentCatalog } from '@/data/agents';

export type DocDifficulty = 'beginner' | 'intermediate' | 'advanced';

export interface DocCategory {
  id: string;
  title: string;
  description: string;
}

export interface DocLink {
  label: string;
  href: string;
}

export interface DocCallout {
  tone: 'warning' | 'tip' | 'important';
  title: string;
  body: string;
}

export interface InternalDoc {
  slug: string;
  title: string;
  category: string;
  description: string;
  readTime: string;
  difficulty: DocDifficulty;
  featured?: boolean;
  intro: string;
  steps: string[];
  examples: string[];
  checklist: string[];
  callouts: DocCallout[];
  relatedLinks: DocLink[];
}

export const docCategories: DocCategory[] = [
  { id: 'quick-start', title: 'البداية السريعة', description: 'ابدأ تشغيل AgentFlow AI بخطوات آمنة وواضحة.' },
  { id: 'agents-tasks', title: 'الوكلاء والمهام', description: 'اختيار الوكيل المناسب وكتابة مهام قابلة للتنفيذ.' },
  { id: 'content-ads', title: 'المحتوى والإعلانات', description: 'إدارة المحتوى، الحزم، القوالب، والنشر الآمن.' },
  { id: 'creative-assets', title: 'الأصول الإبداعية', description: 'إنشاء ورفع وربط الصور والفيديوهات بالمحتوى.' },
  { id: 'providers', title: 'مزودو الخدمات والنشر', description: 'فهم جاهزية OpenAI وMeta وGoogle Ads وPinterest.' },
  { id: 'calendar', title: 'التقويم والجدولة', description: 'جدولة المحتوى ومراقبة التنفيذ بدون مخاطرة.' },
  { id: 'reports-recovery', title: 'التقارير والاسترجاع', description: 'قراءة التقارير وإصلاح حالات الفشل والإعداد الناقص.' },
  { id: 'projects-dev', title: 'المشاريع والتطوير', description: 'تنظيم مشاريع البرمجيات والتسويق والتسليم.' },
  { id: 'prompts-releases', title: 'البرومتات والإصدارات', description: 'حفظ البرومتات وتوثيق الإصدارات بأمان.' },
  { id: 'system-health', title: 'صحة النظام', description: 'معرفة ما يعمل وما يحتاج إصلاحا أولا.' },
  { id: 'safe-deploy', title: 'النشر الآمن', description: 'فحوصات ما قبل النشر على Vercel وبعده.' },
  { id: 'security-admin', title: 'الأمان والإدارة', description: 'الصلاحيات، النسخ الاحتياطي، الفوترة، والتحليلات المتقدمة.' },
  { id: 'best-practices', title: 'أفضل الممارسات', description: 'روتين يومي وأخطاء شائعة يجب تجنبها.' },
];

const commonSafetyCallout: DocCallout = {
  tone: 'warning',
  title: 'تنبيه أمني',
  body: 'لا تضع مفاتيح API أو أسرار أو توكنات أو قيم بيئة خاصة داخل المهام أو البرومتات أو الملاحظات أو تقارير الإصدارات.',
};

const agentNames = agentCatalog.map((agent) => agent.name).join('، ');

export const internalDocs: InternalDoc[] = [
  {
    slug: 'quick-start',
    title: 'دليل البداية السريعة',
    category: 'quick-start',
    description: 'مسار مختصر لتشغيل مساحة العمل من لوحة التحكم حتى أول محتوى أو حملة آمنة.',
    readTime: '6 دقائق',
    difficulty: 'beginner',
    featured: true,
    intro: 'ابدأ دائما من لوحة التحكم ثم افحص صحة النظام قبل إنشاء محتوى أو تشغيل أي إجراء مرتبط بالمزودين.',
    steps: [
      'افتح Dashboard لمراجعة Today’s Actions والاختصارات الأساسية.',
      'افتح System Health وتأكد من عدم وجود Critical أو setup_required يمنع العمل.',
      'افتح Provider Setup Wizard وتحقق من OpenAI أو OpenAI، ثم Meta أو Google Ads أو Pinterest حسب القناة.',
      'أنشئ أول Creative Asset أو ارفع صورة/فيديو إذا كانت الميزة مفعلة في مشروعك.',
      'افتح Content & Ads Studio وأنشئ Draft جديدا للمنصة المناسبة.',
      'استخدم Brand Kit لتوحيد النبرة، العرض، الجمهور، الألوان، CTA والهاشتاغات.',
      'اربط الأصل الإبداعي بالمحتوى ثم انسخ الحزمة أو انشر/جدول فقط عندما تكون الجاهزية واضحة.',
      'راجع Reports وRecovery Center بعد أي محاولة نشر أو جدولة.',
    ],
    examples: [
      'مثال آمن: إنشاء Instagram draft، ربط صورة عامة، ثم نشره فقط بعد ظهور Meta جاهزا.',
      'مثال تشغيلي: إنشاء Google Ads campaign draft متوقف مؤقتا، وليس حملة حية تنفق المال.',
    ],
    checklist: [
      'System Health مفتوح ولا توجد أخطاء حرجة.',
      'Provider Setup يظهر القناة المطلوبة ready أو يوضح السبب.',
      'Brand Kit محدث قبل توليد المحتوى.',
      'الأصل الإبداعي له رابط عام مناسب عند الحاجة.',
      'Reports وRecovery Center تمت مراجعتهما بعد التنفيذ.',
    ],
    callouts: [
      { tone: 'important', title: 'خطوة مهمة', body: 'ابدأ من System Health عندما لا تعرف ما يجب إصلاحه أولا.' },
      commonSafetyCallout,
    ],
    relatedLinks: [
      { label: 'Dashboard', href: '/dashboard' },
      { label: 'System Health', href: '/dashboard/system-health' },
      { label: 'Provider Setup', href: '/dashboard/settings#provider-setup-wizard' },
      { label: 'Content Studio', href: '/dashboard/content-studio' },
      { label: 'Recovery Center', href: '/dashboard/recovery' },
    ],
  },
  {
    slug: 'agents-usage',
    title: 'دليل استخدام الوكلاء الثمانية عشر وما بعدها',
    category: 'agents-tasks',
    description: 'كيف تختار الوكيل المناسب من أقسام الاستراتيجية، النمو، العمليات، والتطوير.',
    readTime: '8 دقائق',
    difficulty: 'beginner',
    featured: true,
    intro: `بدأ AgentFlow AI بثمانية عشر وكيلا عبر Research & Strategy وContent & Growth وSales & Operations، ثم أضيف قسم Development & Engineering لوكلاء التطوير. يعرض التطبيق الوكلاء المتاحين من قاعدة البيانات أو من الكتالوج الاحتياطي. استخدم الاسم الظاهر داخل التطبيق عند إنشاء المهمة. الأسماء الحالية في الكود: ${agentNames}.`,
    steps: [
      'حدد القسم حسب نوع المشكلة: بحث واستراتيجية، محتوى ونمو، مبيعات وعمليات، أو تطوير وهندسة إذا كانت المهمة تقنية.',
      'اختر الوكيل الأقرب للنتيجة المطلوبة بدلا من اختيار وكيل عام.',
      'اكتب عنوانا واضحا يصف المخرج النهائي.',
      'اكتب وصفا يحتوي السياق، الجمهور، القيود، المنصة، ونمط التسليم.',
      'ابدأ المهمة كـ pending ثم شغلها عندما تكون مستعدا.',
      'راجع النتيجة عند needs_review ثم اختر Approve أو Request Changes.',
      'اعتمد completed فقط عندما تكون النتيجة قابلة للاستخدام.',
    ],
    examples: [
      'Market Research Agent: “حلل فرص SaaS لإدارة عيادات الأسنان في الخليج مع أهم 5 شرائح عملاء”.',
      'Copywriting Agent: “اكتب 5 نسخ إعلان LinkedIn لجمهور مؤسسي، نبرة مباشرة، CTA لحجز استشارة”.',
      'Analytics Report Agent: “لخص أداء الشهر من البيانات المتاحة فقط بدون اختراع أرقام”.',
    ],
    checklist: [
      'الوكيل مناسب للتخصص.',
      'الوصف يحتوي هدفا واضحا ومخرجا مطلوبا.',
      'لا توجد أسرار أو مفاتيح داخل المهمة.',
      'تمت مراجعة النتيجة قبل اعتمادها.',
      'تم طلب تعديلات عند وجود نقص بدلا من قبول نتيجة ضعيفة.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'المهمة الجيدة تشبه brief قصير: هدف، جمهور، سياق، قيود، ومخرج نهائي.' },
      commonSafetyCallout,
    ],
    relatedLinks: [
      { label: 'Agents', href: '/dashboard/agents' },
      { label: 'Create Task', href: '/dashboard/create-task' },
      { label: 'Tasks', href: '/dashboard/tasks' },
      { label: 'Reviews', href: '/dashboard/review' },
    ],
  },
  {
    slug: 'tasks-reviews',
    title: 'دليل المهام والمراجعات',
    category: 'agents-tasks',
    description: 'دورة حياة المهمة من الإنشاء حتى الاعتماد النهائي.',
    readTime: '7 دقائق',
    difficulty: 'beginner',
    intro: 'المهام هي طريقة تشغيل الوكلاء بطريقة قابلة للتتبع. دورة الحياة الأساسية هي pending ثم processing ثم needs_review ثم completed، وقد تظهر failed عند حدوث مشكلة.',
    steps: [
      'افتح Create Task.',
      'اختر الوكيل المناسب.',
      'أدخل العنوان والوصف والأولوية.',
      'احفظ المهمة ثم شغلها من صفحة المهمة إذا كانت جاهزة.',
      'عند processing انتظر نتيجة التنفيذ ولا تعدل منطق التشغيل.',
      'عند needs_review اقرأ النتيجة بعناية.',
      'اختر Approve إذا كانت النتيجة مناسبة أو Request Changes إذا احتاجت تعديلا.',
    ],
    examples: [
      'مهمة بحث: “استخرج 10 مشاكل متكررة لدى أصحاب المتاجر الإلكترونية مع اقتراح عرض لكل مشكلة”.',
      'مهمة مراجعة: “حوّل هذه النتيجة إلى قائمة إجراءات يومية بدون إضافة أرقام غير موجودة”.',
    ],
    checklist: [
      'العنوان محدد.',
      'الوصف يحتوي سياقا كافيا.',
      'الأولوية مناسبة.',
      'لم يتم وضع أسرار داخل الوصف.',
      'تمت مراجعة المخرج قبل إغلاق المهمة.',
    ],
    callouts: [
      { tone: 'important', title: 'ما لا يجب لمسه', body: 'n8n/callbacks/webhooks/task execution flow هي طبقة تنفيذ. استخدم الواجهة ولا تعدل التدفق التشغيلي إلا في مرحلة مخصصة لذلك.' },
    ],
    relatedLinks: [
      { label: 'Create Task', href: '/dashboard/create-task' },
      { label: 'Tasks', href: '/dashboard/tasks' },
      { label: 'Reviews', href: '/dashboard/review' },
    ],
  },
  {
    slug: 'content-ads-studio',
    title: 'دليل استوديو المحتوى والإعلانات',
    category: 'content-ads',
    description: 'إنشاء وإدارة محتوى Instagram وFacebook وGoogle Ads وPinterest وLinkedIn.',
    readTime: '9 دقائق',
    difficulty: 'intermediate',
    featured: true,
    intro: 'Content & Ads Studio يجمع مسودات المحتوى وحزم القنوات وإجراءات النشر الآمن. لا تعتبر أي عملية ناجحة حتى يؤكد المزود ذلك في السجلات.',
    steps: [
      'اختر منصة: Instagram أو Facebook أو Google Ads أو Pinterest أو LinkedIn.',
      'أنشئ Draft واكتب الهدف والنص أو استخدم Brand Kit/Template.',
      'اربط Creative Asset عند الحاجة، خاصة Instagram وPinterest.',
      'راجع provider readiness قبل الضغط على أي إجراء نشر.',
      'استخدم Publish to Instagram أو Publish Reel to Instagram أو Publish to Facebook Page أو Publish to Pinterest عندما تكون الجاهزية ready.',
      'استخدم Create Paused Google Ads Campaign Draft وCreate Paused Meta Ad Draft كمسودات متوقفة فقط.',
      'LinkedIn حاليا Manual-only إذا لم يوجد OAuth نشر حقيقي في مشروعك.',
      'انسخ الحزم أو جدولها فقط بعد التأكد من المتطلبات.',
    ],
    examples: [
      'Instagram Post: caption + صورة عامة مستقرة + Meta OAuth + Instagram Business Account.',
      'Google Ads Draft: destination URL + budget notes + keywords/headlines، وينشأ كمسودة متوقفة.',
      'LinkedIn: استخدم النص كحزمة يدوية وانشر خارج النظام إذا كان النشر الآلي غير مفعل.',
    ],
    checklist: [
      'تم اختيار المنصة الصحيحة.',
      'المحتوى ليس فارغا.',
      'الأصل الإبداعي مرتبط عند الحاجة.',
      'provider readiness واضح.',
      'الإعلانات المدفوعة تبقى draft/paused فقط.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'لا تخلط بين organic publishing وبين paid ads. النشر العضوي قد ينشر محتوى، أما الإعلانات المدفوعة فيجب أن تبقى مسودات متوقفة.' },
    ],
    relatedLinks: [
      { label: 'Content Studio', href: '/dashboard/content-studio' },
      { label: 'Creative Assets', href: '/dashboard/creative-assets' },
      { label: 'Provider Setup', href: '/dashboard/settings#provider-setup-wizard' },
      { label: 'Calendar', href: '/dashboard/calendar' },
    ],
  },
  {
    slug: 'creative-assets',
    title: 'دليل الأصول الإبداعية',
    category: 'creative-assets',
    description: 'إدارة الصور والفيديوهات وربطها بالمحتوى والحملات.',
    readTime: '6 دقائق',
    difficulty: 'beginner',
    intro: 'Creative Assets هي مكتبة الصور والفيديوهات والمرئيات المستخدمة في Content Studio وReels والحملات.',
    steps: [
      'افتح Creative Assets.',
      'أنشئ أصلا جديدا أو ارفع صورة/فيديو إذا كانت الميزة مفعلة.',
      'أضف الهدف والجمهور والأسلوب والملاحظات.',
      'استخدم generate prompt عند الحاجة لتجهيز وصف إبداعي.',
      'احفظ الأصل وتأكد من وجود image_url أو storage_path أو public video URL عند الحاجة.',
      'اربط الأصل بعنصر Content Studio.',
      'أزل الربط أو غير الأصل إذا كان الرابط قصير العمر أو غير مناسب للنشر.',
    ],
    examples: [
      'Instagram: صورة مربعة أو 4:5 برابط عام مستقر.',
      'Reel: فيديو عام مناسب وcover إن وجد.',
      'Pinterest: صورة عامة HTTPS وليست رابطا موقعا قصير العمر.',
    ],
    checklist: [
      'العنوان واضح.',
      'نوع الأصل صحيح: image أو video.',
      'الرابط العام متاح عند الحاجة للنشر.',
      'تم الربط بالمحتوى المناسب.',
      'لا توجد أسرار داخل metadata أو الملاحظات.',
    ],
    callouts: [
      { tone: 'important', title: 'خطوة مهمة', body: 'مزودو Instagram وPinterest يحتاجون عادة رابطا عاما مستقرا. الروابط الموقعة قصيرة العمر قد تفشل.' },
    ],
    relatedLinks: [
      { label: 'Creative Assets', href: '/dashboard/creative-assets' },
      { label: 'Content Studio', href: '/dashboard/content-studio' },
      { label: 'System Health', href: '/dashboard/system-health' },
    ],
  },
  {
    slug: 'brand-kit',
    title: 'دليل Brand Kit',
    category: 'content-ads',
    description: 'توحيد هوية العلامة داخل توليد المحتوى والأصول.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    intro: 'Brand Kit يحفظ لغة العلامة حتى لا تبدأ كل مسودة من الصفر.',
    steps: [
      'افتح Settings ثم Brand Kit.',
      'أدخل brand name والعرض الأساسي.',
      'حدد الجمهور المستهدف والنبرة.',
      'أضف الألوان وCTA والهاشتاغات.',
      'استخدم Brand Kit عند إنشاء Content Studio أو Creative Assets.',
      'راجع النتائج وعدلها يدويا قبل النشر.',
    ],
    examples: [
      'نبرة: عملية، واثقة، مباشرة.',
      'CTA: احجز استشارة، جرّب العرض، اطلب الخطة.',
    ],
    checklist: [
      'اسم العلامة صحيح.',
      'العرض التجاري واضح.',
      'الجمهور محدد.',
      'النبرة لا تتعارض مع المنصة.',
      'الألوان والهاشتاغات محدثة.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'Brand Kit الجيد يقلل وقت التحرير، لكنه لا يلغي المراجعة البشرية.' },
    ],
    relatedLinks: [
      { label: 'Settings', href: '/dashboard/settings#brand-kit' },
      { label: 'Content Studio', href: '/dashboard/content-studio' },
      { label: 'Creative Assets', href: '/dashboard/creative-assets' },
    ],
  },
  {
    slug: 'campaign-templates',
    title: 'دليل قوالب الحملات',
    category: 'content-ads',
    description: 'استخدام القوالب بسرعة بدون الكتابة فوق المدخلات الحالية.',
    readTime: '5 دقائق',
    difficulty: 'intermediate',
    intro: 'Campaign Templates تساعدك على إنشاء حزم متكررة مثل Instagram campaign أو Google Ads draft أو Weekly Content Pack.',
    steps: [
      'افتح Content Studio أو منطقة Campaign Planner إذا كانت موجودة.',
      'اختر قالبا مناسبا للمنصة.',
      'راجع الحقول التي سيملؤها القالب.',
      'استخدم Brand Kit لتحسين النصوص.',
      'انتبه لسلوك no-overwrite: الحقول المكتوبة مسبقا لا يجب استبدالها بدون قصد.',
      'راجع الناتج قبل الحفظ أو الجدولة.',
    ],
    examples: [
      'Instagram Template: hook + caption + hashtags.',
      'Google Ads Template: headlines + descriptions + keywords.',
      'Pinterest Template: title + description + destination URL.',
      'Weekly Content Pack: مجموعة مسودات للأسبوع.',
    ],
    checklist: [
      'القالب مناسب للمنصة.',
      'Brand Kit محدث.',
      'لم يتم استبدال حقول مهمة بدون قصد.',
      'تمت مراجعة النصوص قبل النشر.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'ابدأ بالقالب ثم خصصه للسياق، ولا تنشر النص كما هو بدون مراجعة.' },
    ],
    relatedLinks: [
      { label: 'Content Studio', href: '/dashboard/content-studio' },
      { label: 'Campaigns', href: '/dashboard/campaigns' },
      { label: 'Brand Kit', href: '/dashboard/settings#brand-kit' },
    ],
  },
  {
    slug: 'provider-setup',
    title: 'دليل إعداد المزودين',
    category: 'providers',
    description: 'فهم حالات جاهزية المزودين بدون عرض أي أسرار.',
    readTime: '8 دقائق',
    difficulty: 'intermediate',
    featured: true,
    intro: 'Provider Setup Wizard يعرض جاهزية الخدمات الخارجية بلغة تشغيلية واضحة. سترى هل الإعداد موجود أو ناقص أو ينتظر موافقة، لكن لن ترى أي قيمة سرية أو token أو API key.',
    steps: [
      'افتح Settings ثم Provider Setup Wizard.',
      'راجع OpenAI وOpenAI لتوليد النصوص أو الصور حسب إعداد المشروع.',
      'راجع Meta / Instagram / Facebook: OAuth، الصلاحيات، Page، Instagram Business Account.',
      'راجع Google Ads: env vars، OAuth، customer ID، developer token approval.',
      'راجع Pinterest: app/client ID، secret، redirect، OAuth، board.',
      'تذكر أن LinkedIn manual_only إذا لم يكن OAuth publishing مفعلا.',
      'راجع Scheduler وSupabase Storage للأتمتة والوسائط.',
    ],
    examples: [
      'ready: كل متطلب قابل للتحقق متاح.',
      'setup_required: يوجد متطلب ناقص.',
      'approval_pending: يحتاج موافقة خارجية مثل Google Ads developer token.',
      'manual_only: النظام يدعم النسخ/التسليم اليدوي فقط.',
    ],
    checklist: [
      'لا توجد قيم أسرار ظاهرة.',
      'القناة المطلوبة ready قبل النشر.',
      'Google Ads approval مفهوم قبل إنشاء drafts.',
      'Pinterest board محدد عند استخدام Pinterest.',
      'Storage bucket جاهز للأصول.',
    ],
    callouts: [commonSafetyCallout],
    relatedLinks: [
      { label: 'Provider Setup', href: '/dashboard/settings#provider-setup-wizard' },
      { label: 'System Health', href: '/dashboard/system-health' },
      { label: 'Recovery Center', href: '/dashboard/recovery' },
    ],
  },
  {
    slug: 'publishing-safety',
    title: 'دليل أمان النشر والإعلانات',
    category: 'providers',
    description: 'قواعد السلامة بين النشر العضوي والإعلانات المدفوعة.',
    readTime: '7 دقائق',
    difficulty: 'advanced',
    intro: 'قاعدة AgentFlow AI الأساسية: لا توجد نجاحات وهمية، ولا إنفاق حي بدون تأكيد ومراجعة.',
    steps: [
      'افصل بين organic post وpaid ad في ذهنك وداخل المسودات.',
      'لا تعتبر status published إلا عند تأكيد المزود.',
      'استخدم Google Ads paused campaign draft فقط للحملات المدفوعة.',
      'استخدم Meta paid ads paused draft فقط ولا تجعلها live.',
      'لا يعتمد Scheduler إنشاء paid ads تلقائيا.',
      'راجع Recovery Center عند فشل أي محاولة.',
    ],
    examples: [
      'مسموح: Publish to Facebook Page لمنشور عضوي جاهز.',
      'مسموح: Create Paused Google Ads Campaign Draft.',
      'غير آمن: زر عام ينشئ حملة مدفوعة live بدون مراجعة.',
    ],
    checklist: [
      'provider readiness ready.',
      'لا يوجد fake success.',
      'الإعلانات المدفوعة paused/draft فقط.',
      'تمت مراجعة الصفحة أو الحساب المختار.',
      'تم تسجيل محاولة النشر أو سبب الفشل.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'لا تضغط إجراء نشر إذا كانت الجاهزية setup_required أو token_missing أو approval_pending.' },
    ],
    relatedLinks: [
      { label: 'Content Studio', href: '/dashboard/content-studio' },
      { label: 'Provider Setup', href: '/dashboard/settings#provider-setup-wizard' },
      { label: 'Recovery Center', href: '/dashboard/recovery' },
    ],
  },
  {
    slug: 'content-calendar',
    title: 'دليل التقويم وجدولة المحتوى',
    category: 'calendar',
    description: 'قراءة التقويم وجدولة المحتوى بطريقة آمنة.',
    readTime: '6 دقائق',
    difficulty: 'intermediate',
    intro: 'Calendar يعرض المحتوى المجدول وحالاته. الجدولة لا تعني أن النشر سينجح إذا كان المزود غير جاهز.',
    steps: [
      'افتح Calendar.',
      'راجع العناصر scheduled وready وfailed.',
      'حدد وقت النشر المناسب.',
      'تأكد من provider readiness قبل موعد التنفيذ.',
      'إذا كان setup_required سيظهر السبب في السجل أو Recovery Center.',
      'استخدم Scheduler فقط للمحتوى العضوي المدعوم.',
    ],
    examples: [
      'Instagram post مجدول يحتاج caption وصورة عامة وInstagram Business Account.',
      'Paid ad draft لا يجب أن ينشئه scheduler كحملة حية.',
    ],
    checklist: [
      'التاريخ والوقت صحيحان.',
      'المحتوى ready أو scheduled.',
      'المزود جاهز.',
      'لا توجد أصول ناقصة.',
      'Recovery Center خال من فشل متعلق بالعنصر.',
    ],
    callouts: [
      { tone: 'important', title: 'خطوة مهمة', body: 'إذا كان إعداد المزود ناقصا وقت الجدولة، سيبقى العنصر بحاجة إصلاح بدلا من إعلان نجاح وهمي.' },
    ],
    relatedLinks: [
      { label: 'Calendar', href: '/dashboard/calendar' },
      { label: 'Content Studio', href: '/dashboard/content-studio' },
      { label: 'System Health', href: '/dashboard/system-health' },
    ],
  },
  {
    slug: 'recovery-center',
    title: 'دليل مركز الاسترجاع',
    category: 'reports-recovery',
    description: 'فهم الحالات التي تحتاج إصلاحا وكيفية العودة للمسار الصحيح.',
    readTime: '6 دقائق',
    difficulty: 'beginner',
    intro: 'Recovery Center هو المكان الذي تذهب إليه عندما يفشل نشر أو ينقص إعداد أو يحتاج مزود لموافقة.',
    steps: [
      'افتح Recovery Center.',
      'ابدأ بالحالات failed ثم setup_required ثم token_missing.',
      'اقرأ reason وnext action.',
      'افتح العنصر المرتبط أو Provider Setup عند الحاجة.',
      'بعد الإصلاح، أعد المحاولة من المكان المناسب وليس من طبقة التنفيذ الداخلية.',
      'انسخ recovery report عند الحاجة لتوثيق الحالة.',
    ],
    examples: [
      'setup_required: Instagram Business Account غير محدد.',
      'approval_pending: Google Ads developer token يحتاج مراجعة.',
      'manual_only: LinkedIn planner يحتاج نشر يدوي.',
      'unsupported: نوع محتوى غير مدعوم للنشر الآلي.',
    ],
    checklist: [
      'تم فتح المشكلة الأصلية.',
      'تم فهم الحالة.',
      'تم تنفيذ next action.',
      'لم يتم تعديل callbacks/webhooks.',
      'تمت إعادة المحاولة من الواجهة الآمنة.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'System Health يعطيك الصورة العامة، وRecovery Center يعطيك قائمة الإصلاحات العملية.' },
    ],
    relatedLinks: [
      { label: 'Recovery Center', href: '/dashboard/recovery' },
      { label: 'System Health', href: '/dashboard/system-health' },
      { label: 'Content Studio', href: '/dashboard/content-studio' },
    ],
  },
  {
    slug: 'reports',
    title: 'دليل التقارير',
    category: 'reports-recovery',
    description: 'قراءة تقارير التشغيل بدون اختراع مؤشرات أداء.',
    readTime: '6 دقائق',
    difficulty: 'beginner',
    intro: 'Reports يعرض ملخصات شهرية وتشغيلية من البيانات الموجودة فقط: جاهزية المزودين، عدادات المحتوى، محاولات النشر، وحالة الجدولة.',
    steps: [
      'افتح Reports.',
      'راجع Monthly Report إذا كان متاحا.',
      'راجع Provider Readiness لمعرفة القنوات الجاهزة.',
      'راجع Content Counts وPublish Attempts.',
      'راجع Scheduler Summary للعناصر المجدولة.',
      'انسخ أو صدر التقرير إذا كانت أدوات التصدير موجودة.',
    ],
    examples: [
      'يعرض عدد published الحقيقي من السجلات.',
      'لا يعرض clicks/impressions/spend إلا إذا جاءت من مزود حقيقي.',
    ],
    checklist: [
      'لا توجد أرقام أداء وهمية.',
      'الملخص مبني على workspace الحالي.',
      'تمت مراجعة provider blockers.',
      'تم نسخ التقرير عند الحاجة للتوثيق.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'لا تستخدم التقارير كبديل عن لوحة المزود إذا احتجت أرقام إعلانات دقيقة غير متاحة داخل النظام.' },
    ],
    relatedLinks: [
      { label: 'Reports', href: '/dashboard/reports' },
      { label: 'Recovery Center', href: '/dashboard/recovery' },
      { label: 'System Health', href: '/dashboard/system-health' },
    ],
  },
  {
    slug: 'projects',
    title: 'دليل المشاريع',
    category: 'projects-dev',
    description: 'تنظيم مشاريع البرمجيات والتسويق وربطها بالإصدارات والمهام.',
    readTime: '6 دقائق',
    difficulty: 'beginner',
    intro: 'Projects يساعدك على إدارة مشاريع كبيرة داخل الوكالة: SaaS، موقع، أتمتة، حملة تسويق، أو نظام داخلي.',
    steps: [
      'افتح Projects.',
      'أنشئ Project جديدا.',
      'حدد type وstatus وpriority.',
      'أضف GitHub URL وproduction URL وstaging URL إذا وجدت.',
      'أضف notes وknown issues وروابط التوثيق.',
      'اربط releases والمهام بالمشروع عند الحاجة.',
      'استخدم الحالة ready_to_deploy فقط عندما تكتمل الفحوصات.',
    ],
    examples: [
      'مشروع برمجي: GitHub URL + production URL + notes + releases.',
      'حملة تسويق: أهداف، محتوى مرتبط، أصول إبداعية، ومهام للوكلاء.',
    ],
    checklist: [
      'اسم المشروع واضح.',
      'الحالة تعكس الواقع.',
      'روابط الإنتاج أو GitHub صحيحة.',
      'الملاحظات لا تحتوي أسرارا.',
      'يوجد release عند التسليم.',
    ],
    callouts: [commonSafetyCallout],
    relatedLinks: [
      { label: 'Projects', href: '/dashboard/projects' },
      { label: 'Releases', href: '/dashboard/releases' },
      { label: 'Tasks', href: '/dashboard/tasks' },
    ],
  },
  {
    slug: 'prompt-library',
    title: 'دليل مكتبة البرومتات',
    category: 'prompts-releases',
    description: 'حفظ البرومتات وإعادة استخدامها بأمان.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    intro: 'Prompt Library تحفظ البرومتات الجيدة حسب الفئة والأداة المستهدفة حتى لا تعيد كتابتها كل مرة.',
    steps: [
      'افتح Prompt Library.',
      'أنشئ prompt جديدا بعنوان واضح.',
      'حدد category وtarget tool.',
      'اكتب البرومت بطريقة قابلة لإعادة الاستخدام.',
      'استخدم favorite للبرومتات المهمة.',
      'انسخ البرومت عند الحاجة للأداة المناسبة.',
      'استورد starter prompts إذا كانت الميزة موجودة.',
    ],
    examples: [
      'Prompt لتجهيز release report.',
      'Prompt لمراجعة صفحة تسويقية.',
      'Prompt لفحص migration قبل deploy.',
    ],
    checklist: [
      'العنوان يشرح الاستخدام.',
      'التصنيف صحيح.',
      'الأداة المستهدفة صحيحة.',
      'لا توجد أسرار أو توكنات.',
      'تم تحديث البرومت عند تحسن الطريقة.',
    ],
    callouts: [commonSafetyCallout],
    relatedLinks: [
      { label: 'Prompt Library', href: '/dashboard/prompt-library' },
      { label: 'Create Task', href: '/dashboard/create-task' },
    ],
  },
  {
    slug: 'release-manager',
    title: 'دليل إدارة الإصدارات',
    category: 'prompts-releases',
    description: 'توثيق الإصدار والفحوصات والروابط وملاحظات الرجوع.',
    readTime: '6 دقائق',
    difficulty: 'intermediate',
    intro: 'Release Manager يحول كل مرحلة تطوير إلى سجل قابل للمراجعة قبل وبعد النشر.',
    steps: [
      'افتح Releases.',
      'أنشئ release جديدا.',
      'أدخل version وphase name وsummary.',
      'وثق files changed وfeatures added وfixes.',
      'أدخل نتائج build/lint/typecheck/deploy.',
      'أضف deploy URL وproduction URL إن وجدت.',
      'سجل known issues وrollback notes.',
      'انسخ release report عند التسليم.',
    ],
    examples: [
      'Phase 12: Internal Documentation Center.',
      'Status: ready_to_deploy بعد نجاح lint وtsc وbuild.',
    ],
    checklist: [
      'النسخة أو المرحلة واضحة.',
      'الفحوصات مكتوبة بصدق.',
      'روابط النشر صحيحة.',
      'known issues مذكورة.',
      'rollback notes موجودة عند الحاجة.',
    ],
    callouts: [
      { tone: 'important', title: 'خطوة مهمة', body: 'لا تضع release كـ deployed قبل التحقق من الإنتاج أو الرابط المنشور.' },
    ],
    relatedLinks: [
      { label: 'Releases', href: '/dashboard/releases' },
      { label: 'Projects', href: '/dashboard/projects' },
      { label: 'System Health', href: '/dashboard/system-health' },
    ],
  },
  {
    slug: 'system-health',
    title: 'دليل صحة النظام',
    category: 'system-health',
    description: 'كيف تقرأ Health Score وتعرف ما يجب إصلاحه أولا.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    featured: true,
    intro: 'System Health Center يعطيك رؤية تشغيلية: ما يعمل، ما يحتاج إعدادا، ما ينتظر موافقة، وما يجب إصلاحه بعد ذلك.',
    steps: [
      'افتح System Health.',
      'اقرأ Health Score والتصنيف.',
      'راجع Top Blockers الثلاثة الأولى.',
      'افتح Provider Health لمعرفة حالة كل مزود.',
      'راجع Env Presence كحضور فقط بدون قيم.',
      'راجع Operational Health للمهام والمحتوى والإصدارات.',
      'انسخ System Health Report عند الحاجة.',
    ],
    examples: [
      'score منخفض بسبب CRON_SECRET مفقود وPinterest board غير محدد.',
      'manual_only في LinkedIn ليس خطأ، بل طريقة تشغيل يدوية.',
    ],
    checklist: [
      'لا توجد errors حرجة.',
      'المزود المطلوب ready.',
      'Storage جاهز.',
      'Top Issues لها إجراءات واضحة.',
      'التقرير لا يحتوي أسرارا.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'عندما تكون محتارا، أصلح أول عنصر في Top Issues ثم أعد فحص الصفحة.' },
    ],
    relatedLinks: [
      { label: 'System Health', href: '/dashboard/system-health' },
      { label: 'Provider Setup', href: '/dashboard/settings#provider-setup-wizard' },
      { label: 'Recovery Center', href: '/dashboard/recovery' },
    ],
  },
  {
    slug: 'vercel-deployment',
    title: 'دليل النشر الآمن على Vercel',
    category: 'safe-deploy',
    description: 'قائمة نشر آمنة قبل الإنتاج وبعده.',
    readTime: '7 دقائق',
    difficulty: 'advanced',
    intro: 'النشر الآمن يبدأ بفحوصات محلية واضحة ثم migrations ثم deploy ثم smoke test.',
    steps: [
      'شغل npm run lint.',
      'شغل npx tsc --noEmit.',
      'شغل npm run build.',
      'طبق migrations أولا إذا كانت مطلوبة.',
      'انشر باستخدام npx vercel --prod عندما تكون جاهزا.',
      'استخدم أمر deploy بديل فقط إذا كان موثقا في مشروعك.',
      'نفذ smoke test للمسارات الأساسية بعد النشر.',
      'راجع System Health وReports بعد النشر.',
    ],
    examples: [
      'Smoke test: /dashboard، /dashboard/content-studio، /dashboard/projects، /dashboard/releases، /dashboard/system-health، /dashboard/docs.',
      'لا تعرض env values في لقطات شاشة أو تقارير.',
    ],
    checklist: [
      'lint passed.',
      'typecheck passed.',
      'build passed.',
      'migrations مطبقة إن وجدت.',
      'production route يفتح.',
      'لا توجد أسرار في logs أو docs.',
    ],
    callouts: [commonSafetyCallout],
    relatedLinks: [
      { label: 'Releases', href: '/dashboard/releases' },
      { label: 'Projects', href: '/dashboard/projects' },
      { label: 'System Health', href: '/dashboard/system-health' },
    ],
  },
  {
    slug: 'daily-workflow',
    title: 'طريقة العمل اليومية',
    category: 'best-practices',
    description: 'روتين صباحي ومنتصف اليوم ومساء لإدارة الوكالة.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    intro: 'استخدم هذا الروتين لتجنب العمل العشوائي والحفاظ على النظام نظيفا.',
    steps: [
      'صباحا: افتح Dashboard وراجع Today’s Actions.',
      'صباحا: افحص System Health ثم Recovery Center.',
      'منتصف اليوم: أنشئ حملات أو محتوى جديدا باستخدام القوالب وBrand Kit.',
      'منتصف اليوم: استخدم الوكلاء للبحث والكتابة والتحليل.',
      'منتصف اليوم: اربط الأصول الإبداعية بالمحتوى.',
      'مساء: راجع Calendar للعناصر المجدولة.',
      'مساء: راجع Reports وأنشئ next actions لليوم التالي.',
    ],
    examples: [
      'إذا ظهر provider issue صباحا، أصلحه قبل إنشاء محتوى جديد لنفس المنصة.',
      'إذا اكتملت مهمة needs_review مساء، اعتمدها أو اطلب تعديلا قبل أن تتراكم.',
    ],
    checklist: [
      'Today’s Actions تمت مراجعتها.',
      'System Health لا يحتوي blocker غير مفهوم.',
      'Recovery Center تمت مراجعته.',
      'Calendar محدث.',
      'Next actions واضحة لليوم التالي.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'أفضل استخدام للنظام هو تشغيله كروتين يومي قصير، لا كمخزن عشوائي للمهام.' },
    ],
    relatedLinks: [
      { label: 'Dashboard', href: '/dashboard' },
      { label: 'Calendar', href: '/dashboard/calendar' },
      { label: 'Reports', href: '/dashboard/reports' },
      { label: 'Recovery Center', href: '/dashboard/recovery' },
    ],
  },
  {
    slug: 'common-mistakes',
    title: 'أخطاء يجب تجنبها',
    category: 'best-practices',
    description: 'أكثر الأخطاء التي تسبب فشل التشغيل أو نتائج ضعيفة.',
    readTime: '6 دقائق',
    difficulty: 'beginner',
    intro: 'هذه قائمة مختصرة بالأخطاء التي تؤدي غالبا إلى نتائج ضعيفة أو فشل نشر أو مخاطر أمنية.',
    steps: [
      'لا تكتب وصف مهمة غامضا.',
      'لا تختر وكيلا غير مناسب فقط لأنه عام.',
      'لا تنشر قبل provider readiness.',
      'لا تخلط organic posts مع paid ads.',
      'لا تستخدم روابط وسائط قصيرة العمر للنشر.',
      'لا تنس migrations قبل deploy.',
      'لا تخزن secrets داخل prompts أو notes أو releases.',
      'لا تعتمد على زر Publish عام بدون فهم الإجراء.',
      'لا تتجاوز الاختبار النهائي.',
    ],
    examples: [
      'خطأ: “اكتب حملة جيدة”. الأفضل: “اكتب 5 منشورات Instagram لجمهور SaaS عربي بنبرة عملية وCTA لحجز استشارة”.',
      'خطأ: وضع API key في Prompt Library. الصحيح: ضعها فقط في env manager الآمن.',
    ],
    checklist: [
      'المهام واضحة.',
      'المزود جاهز قبل النشر.',
      'الإعلانات المدفوعة paused/draft.',
      'الروابط العامة مستقرة.',
      'الأسرار ليست في أي نص داخلي.',
      'تم تشغيل lint/typecheck/build قبل النشر.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'أغلب المشاكل التشغيلية تأتي من استعجال النشر قبل الجاهزية أو من وصف مهام غير واضح.' },
      commonSafetyCallout,
    ],
    relatedLinks: [
      { label: 'System Health', href: '/dashboard/system-health' },
      { label: 'Provider Setup', href: '/dashboard/settings#provider-setup-wizard' },
      { label: 'Prompt Library', href: '/dashboard/prompt-library' },
    ],
  },
  {
    slug: 'development-engineering-agents',
    title: 'دليل وكلاء التطوير والهندسة',
    category: 'agents-tasks',
    description: 'شرح قسم Development & Engineering وكيف تستخدم وكلاء التطوير مع المشاريع والتحليل والإصدارات.',
    readTime: '7 دقائق',
    difficulty: 'intermediate',
    featured: true,
    intro: 'قسم Development & Engineering يساعد المدير على تخطيط ومراجعة وتصحيح وتوثيق واختبار ونشر مشاريع البرمجيات داخل AgentFlow AI بدون تعديل الكود تلقائيا.',
    steps: [
      'استخدم Code Review Agent لمراجعة جودة الكود والمخاطر قبل الإصدار.',
      'استخدم Bug Fix Agent لتحليل الأخطاء والـ logs ووضع خطة إصلاح آمنة.',
      'استخدم Architecture Agent لتخطيط البنية، تدفق البيانات، والخطوات التنفيذية.',
      'استخدم Testing Agent لإنشاء QA checklist واختبارات smoke وedge cases.',
      'استخدم Documentation Agent لكتابة أدلة داخلية، تقارير، release notes وFAQ.',
      'استخدم Deployment Agent لتجهيز Vercel checklist، migrations، smoke tests وrollback.',
      'استخدم Security Review Agent لفحص الأسرار، RLS، OAuth، uploads، والتوكنات.',
      'استخدم Database Agent لتخطيط Supabase schema، migrations، RLS، indexes والعلاقات.',
      'استخدم UI/UX Review Agent لمراجعة الواجهات، القراءة، المسافات، الاستجابة والموبايل.',
    ],
    examples: [
      'من صفحة Project افتح Developer Agent Shortcuts ثم اختر Ask Code Review Agent لإنشاء مهمة مراجعة مرتبطة بالمشروع.',
      'بعد Codebase Analyzer، أنشئ مهمة للـ Security Review Agent إذا ظهرت ملاحظة عن auth أو secrets.',
      'من Software Planner، استخدم Architecture Agent وDatabase Agent وTesting Agent لتحويل الخطة إلى مهام pending فقط.',
    ],
    checklist: [
      'المهمة تحتوي project context واضح.',
      'لا توجد أسرار أو API keys أو tokens داخل الوصف.',
      'المخرجات المطلوبة report أو checklist أو plan فقط.',
      'المهمة تبقى pending ولا يتم تشغيلها تلقائيا.',
      'لا يوجد push أو PR أو deploy من داخل مهمة الوكيل.',
    ],
    callouts: [
      { tone: 'important', title: 'حدود آمنة', body: 'وكلاء التطوير يقدمون خططا وتقارير وقوائم فحص. لا يعدلون الكود ولا يدفعون commits ولا ينشرون تلقائيا.' },
      commonSafetyCallout,
    ],
    relatedLinks: [
      { label: 'Agents', href: '/dashboard/agents?department=Development%20%26%20Engineering' },
      { label: 'Projects', href: '/dashboard/projects' },
      { label: 'Software Planner', href: '/dashboard/software-planner' },
      { label: 'Prompt Library', href: '/dashboard/prompt-library' },
      { label: 'Releases', href: '/dashboard/releases' },
    ],
  },
  {
    slug: 'dashboard-guide',
    title: 'دليل لوحة التحكم',
    category: 'quick-start',
    description: 'كيف تقرأ لوحة التحكم اليومية وتستخدم الاختصارات بدون تغيير أي منطق تشغيلي.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    intro: 'لوحة التحكم هي نقطة البداية اليومية. تعرض المهام، الجاهزية، المحاولات، الاختصارات، والتنبيهات بصورة تشغيلية مختصرة.',
    steps: [
      'افتح /dashboard بعد تسجيل الدخول.',
      'راجع مؤشرات المهام والمحتوى ومحاولات النشر.',
      'ابدأ من Today’s Actions إذا ظهرت مشكلة setup_required أو failed.',
      'استخدم الاختصارات لفتح الصفحات المتخصصة بدلا من تنفيذ قرارات حساسة من لوحة واحدة.',
      'راجع Publish & Scheduler Attempts ولا تعتبر أي عنصر منشورا إلا إذا كان السجل مؤكد النجاح.',
      'افتح System Health عند وجود أكثر من مشكلة لتحديد الأولوية.',
    ],
    examples: [
      'إذا ظهرت مشكلة provider setup، افتح Settings ثم Provider Setup Wizard.',
      'إذا ظهر فشل نشر، افتح Recovery Center واقرأ السبب قبل إعادة المحاولة.',
    ],
    checklist: [
      'المؤشرات مفهومة ولا تعرض أسرارا.',
      'الاختصارات تقود لصفحات العمل الصحيحة.',
      'الرسوم والحركة لا تمنع قراءة المحتوى.',
      'كل قرار نشر أو تشغيل يتم من الصفحة المتخصصة فقط.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'استعمل لوحة التحكم كمركز قراءة وتوجيه، وليس كمكان لتجاوز فحوصات الجاهزية.' },
      commonSafetyCallout,
    ],
    relatedLinks: [
      { label: 'Dashboard', href: '/dashboard' },
      { label: 'System Health', href: '/dashboard/system-health' },
      { label: 'Recovery Center', href: '/dashboard/recovery' },
    ],
  },
  {
    slug: 'content-library',
    title: 'دليل Content Library',
    category: 'content-ads',
    description: 'مراجعة عناصر المحتوى المنشأة وحالات النشر والجدولة من مكان واحد.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    intro: 'Content Library تعرض السجل المنظم لعناصر Content Studio. هي للبحث والمراجعة والفتح، وليست بديلا عن فحوصات المزودين.',
    steps: [
      'افتح /dashboard/content-library إذا كان هذا المسار موجودا.',
      'استخدم البحث والفلاتر حسب النوع أو الحالة أو المنصة.',
      'افتح العنصر لمراجعة النص، الحالة، آخر محاولة، والروابط المرتبطة.',
      'إذا كان العنصر مدفوعا، تأكد أن الإجراء Draft/Paused ولا يصرف المال.',
      'ارجع إلى Content Studio للتعديل أو الإجراء العملي.',
    ],
    examples: [
      'فلتر Instagram لمعرفة المنشورات الجاهزة للنشر العضوي.',
      'فلتر Google Ads Draft لمراجعة المسودات المتوقفة فقط.',
    ],
    checklist: [
      'لا توجد توكنات أو ردود خام من المزودين.',
      'حالة Published تعني سجلا مؤكدا من المزود أو النظام.',
      'الأزرار توجه إلى Open Guide أو فتح العنصر بوضوح.',
      'الإعلانات المدفوعة لا تظهر كـ Publish.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'هذه الصفحة لا تصرف المال ولا تنشر تلقائيا. أي إجراء حقيقي يجب أن يمر من صفحة العنصر وفحص الجاهزية.' },
    ],
    relatedLinks: [
      { label: 'Content Library', href: '/dashboard/content-library' },
      { label: 'Content Studio', href: '/dashboard/content-studio' },
      { label: 'Publishing Safety', href: '/dashboard/docs/publishing-safety' },
    ],
  },
  {
    slug: 'notifications-center',
    title: 'دليل Notifications Center',
    category: 'reports-recovery',
    description: 'قراءة التنبيهات التشغيلية بدون كشف أسرار أو توكنات.',
    readTime: '4 دقائق',
    difficulty: 'beginner',
    intro: 'Notifications Center يجمع تنبيهات المهام، الجاهزية، النشر، الإعداد، والتحذيرات. التنبيهات مختصرة ويجب ألا تحتوي قيما سرية.',
    steps: [
      'افتح /dashboard/notifications إذا كان هذا المسار موجودا.',
      'ابدأ بالتنبيهات غير المقروءة.',
      'استخدم الفلاتر لعرض publishing أو setup أو tasks.',
      'افتح الرابط المرتبط بالتنبيه إن وجد.',
      'لا تنسخ أي معلومات حساسة داخل تعليق أو مهمة.',
    ],
    examples: [
      'تنبيه task_needs_review يعني أن النتيجة جاهزة للمراجعة، وليس اعتمادا تلقائيا.',
      'تنبيه provider_setup_required يعني أن المزود يحتاج إعدادا قبل الإجراء.',
    ],
    checklist: [
      'التنبيه لا يحتوي أسرارا.',
      'الرسالة توضح الإجراء التالي.',
      'تم فتح الصفحة المرتبطة قبل اتخاذ قرار.',
      'تم تعليم التنبيه كمقروء بعد معالجته.',
    ],
    callouts: [
      { tone: 'important', title: 'خطوة مهمة', body: 'إذا كان التنبيه عن setup_required، افتح Provider Setup Wizard بدلا من تكرار المحاولة.' },
    ],
    relatedLinks: [
      { label: 'Notifications', href: '/dashboard/notifications' },
      { label: 'Settings', href: '/dashboard/settings' },
      { label: 'Recovery Center', href: '/dashboard/recovery' },
    ],
  },
  {
    slug: 'settings-guide',
    title: 'دليل Settings',
    category: 'security-admin',
    description: 'شرح أقسام الإعدادات: Workspace وBrand Kit وAppearance وProviders والأمان والنسخ والفوترة.',
    readTime: '7 دقائق',
    difficulty: 'beginner',
    intro: 'Settings تجمع إعدادات مساحة العمل والهوية والجاهزية. القيم السرية لا تعرض هنا؛ تظهر فقط حالات present أو missing أو setup_required.',
    steps: [
      'ابدأ من Workspace لمراجعة الحساب ومساحة العمل.',
      'حدث Brand Kit قبل توليد محتوى جديد.',
      'استخدم Appearance & Theme لتعديل الشكل ثم Reset to Default عند الحاجة.',
      'راجع Providers لمعرفة OpenAI وOpenAI وMeta وGoogle Ads وPinterest وGitHub وScheduler وSupabase Storage.',
      'افتح Publishing & Scheduling لفهم cron status وجاهزية الجدولة.',
      'راجع Roles & Permissions قبل إعطاء أي صلاحية حساسة.',
      'استخدم Security وBackups وBilling كروابط إدارة هادئة ومحمية.',
      'اترك Advanced للأفعال الحساسة والتحذيرات فقط.',
    ],
    examples: [
      'زر Save Settings يحفظ القسم الحالي فقط.',
      'زر Reset to Default يعيد إعدادات الشكل الافتراضية ولا يغير الأسرار.',
    ],
    checklist: [
      'لا توجد قيم raw secret في الواجهة.',
      'كل مزود يعرض حالة واضحة.',
      'الإعدادات الحساسة محصورة في owner/admin إذا كانت الأدوار مفعلة.',
      'الفوترة لا تظهر معلومات حساسة.',
    ],
    callouts: [
      { tone: 'warning', title: 'أمان', body: 'لا تدخل API keys أو refresh tokens داخل Brand Kit أو الملاحظات أو البرومتات. استخدم Vercel Environment Variables فقط.' },
    ],
    relatedLinks: [
      { label: 'Settings', href: '/dashboard/settings' },
      { label: 'Security Center', href: '/dashboard/security' },
      { label: 'Backup Center', href: '/dashboard/backups' },
    ],
  },
  {
    slug: 'security-center',
    title: 'دليل Security Center',
    category: 'security-admin',
    description: 'قراءة فحوصات الأمان المستوحاة من OWASP بدون ادعاء شهادة أو اعتماد رسمي.',
    readTime: '6 دقائق',
    difficulty: 'intermediate',
    intro: 'Security Center يعرض ملخصا لفحوصات المصادقة، الصلاحيات، RLS، الملفات، الأسرار، GitHub، الذكاء الاصطناعي، الجدولة، والنسخ الاحتياطي.',
    steps: [
      'افتح /dashboard/security.',
      'راجع Overall posture ثم Critical أو Warning أولا.',
      'انسخ التقرير عبر Copy Security Report عند الحاجة.',
      'افتح Backup Center أو System Health من الروابط المرتبطة.',
      'لا تعتبر الفحص شهادة OWASP، بل مراجعة hardening مستوحاة من OWASP.',
    ],
    examples: [
      'تحذير provider tokens يعني مراجعة التخزين والسجلات وعدم عرض التوكنات.',
      'تحذير upload safety يعني مراجعة الحجم والنوع والامتداد والمسار.',
    ],
    checklist: [
      'Dashboard routes تتطلب auth.',
      'Server actions تتحقق من المستخدم ومساحة العمل.',
      'النسخ والتقارير لا تعرض أسرارا.',
      'AI Assistant لا ينفذ أفعالا حساسة.',
    ],
    callouts: [
      { tone: 'important', title: 'أمان', body: 'OWASP-inspired security hardening checks were reviewed. هذا لا يعني شهادة امتثال رسمية.' },
      commonSafetyCallout,
    ],
    relatedLinks: [
      { label: 'Security Center', href: '/dashboard/security' },
      { label: 'System Health', href: '/dashboard/system-health' },
      { label: 'Backup Center', href: '/dashboard/backups' },
    ],
  },
  {
    slug: 'backup-center',
    title: 'دليل Backup Center',
    category: 'security-admin',
    description: 'إنشاء نسخة JSON وملخص Markdown آمنين بدون أسرار أو ملفات ثنائية.',
    readTime: '6 دقائق',
    difficulty: 'beginner',
    intro: 'Backup Center يصدر بيانات مساحة العمل القابلة للتوثيق فقط. لا يسترجع البيانات ولا يكتب فوق السجلات ولا يضم ملفات assets الثنائية.',
    steps: [
      'افتح /dashboard/backups.',
      'اختر التصنيفات الآمنة أو All safe workspace data.',
      'اضغط Create Backup.',
      'استخدم Download JSON لحفظ التصدير.',
      'استخدم Copy Backup Summary أو Download Markdown للمراجعة.',
      'راجع Excluded Sensitive Fields قبل مشاركة الملف.',
    ],
    examples: [
      'نسخة قبل إصدار جديد: projects + releases + prompts + content metadata.',
      'ملخص مشاركة داخلي: Markdown فقط بدون JSON كامل.',
    ],
    checklist: [
      'Provider tokens مستبعدة.',
      'API keys وraw env values مستبعدة.',
      'البرومتات التي تشبه الأسرار يتم تنقيحها.',
      'لا توجد restore writes في هذه المرحلة.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'النسخة الاحتياطية لا تحتوي أسرارا ولا ملفات ثنائية. لا تضف أسرارا يدويا إلى JSON بعد تنزيله.' },
    ],
    relatedLinks: [
      { label: 'Backup Center', href: '/dashboard/backups' },
      { label: 'Security Center', href: '/dashboard/security' },
    ],
  },
  {
    slug: 'github-integration',
    title: 'دليل GitHub Integration',
    category: 'projects-dev',
    description: 'استخدام GitHub للقراءة والتحليل وربط المشاريع بدون كتابة أو merge أو comment.',
    readTime: '7 دقائق',
    difficulty: 'intermediate',
    intro: 'GitHub Integration في AgentFlow AI مصمم كمسار قراءة وتخطيط. لا يدمج Pull Requests ولا يعلق ولا يدفع commits إلا إذا تم تنفيذ ميزة كتابة صريحة لاحقا.',
    steps: [
      'أضف GitHub URL داخل Project إذا كانت الميزة مفعلة.',
      'راجع حالة GitHub في Provider Setup Wizard.',
      'إذا لم يوجد token ستظهر setup_required بوضوح.',
      'استخدم Issue to Task لتحويل issue إلى task pending فقط.',
      'استخدم Pull Request Assistant لإنشاء تقرير مراجعة فقط.',
      'لا تعتبر أي تقرير GitHub تعليقا منشورا على GitHub.',
    ],
    examples: [
      'قراءة issues لإنشاء مهام داخلية pending.',
      'قراءة PR diff لإنتاج Generate PR Review داخل التطبيق فقط.',
    ],
    checklist: [
      'GitHub token غير ظاهر في الواجهة.',
      'لا توجد merge/comment/approve actions.',
      'المهام الناتجة pending فقط.',
      'الروابط محفوظة بصيغة HTTPS آمنة.',
    ],
    callouts: [
      { tone: 'important', title: 'أمان', body: 'هذه العملية لا تكتب في GitHub ولا توافق على PR ولا تدمج ولا تعلق.' },
    ],
    relatedLinks: [
      { label: 'Projects', href: '/dashboard/projects' },
      { label: 'Provider Setup', href: '/dashboard/settings#provider-setup-wizard' },
    ],
  },
  {
    slug: 'github-issue-to-task',
    title: 'دليل GitHub Issue to Task Automation',
    category: 'projects-dev',
    description: 'تحويل GitHub issues إلى مهام داخلية pending مع تنقيح النصوص.',
    readTime: '5 دقائق',
    difficulty: 'intermediate',
    intro: 'Issue to Task يساعدك على تحويل issue إلى مهمة داخل AgentFlow AI. العملية لا تغلق issue ولا تكتب تعليقا في GitHub.',
    steps: [
      'افتح Project يحتوي GitHub URL صالحا.',
      'راجع قائمة issues إذا كان GitHub جاهزا.',
      'اقرأ العنوان والوصف والتسميات.',
      'اضغط Create Task لإنشاء مهمة pending فقط.',
      'افتح المهمة وراجع النص قبل التشغيل.',
    ],
    examples: [
      'Issue عن bug يتحول إلى مهمة Bug Fix Agent pending.',
      'Issue عن docs يتحول إلى مهمة Documentation Agent pending.',
    ],
    checklist: [
      'نص issue منقح من الأسرار قدر الإمكان.',
      'المهمة لا تعمل تلقائيا.',
      'لا يوجد GitHub write.',
      'تمت مراجعة المهمة قبل Run Task.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'إذا كان issue يحتوي سرا، احذف السر من GitHub ومن المهمة ولا تنسخه إلى أي تقرير.' },
    ],
    relatedLinks: [
      { label: 'Projects', href: '/dashboard/projects' },
      { label: 'Tasks', href: '/dashboard/tasks' },
    ],
  },
  {
    slug: 'pull-request-assistant',
    title: 'دليل Pull Request Assistant',
    category: 'projects-dev',
    description: 'إنشاء مراجعة PR داخلية فقط بدون merge أو approve أو comment.',
    readTime: '6 دقائق',
    difficulty: 'intermediate',
    intro: 'Pull Request Assistant يقرأ بيانات PR إذا كانت GitHub جاهزة، ثم يولد تقرير مراجعة داخلي. لا ينفذ أي إجراء داخل GitHub.',
    steps: [
      'افتح Project مرتبط بمستودع GitHub.',
      'اختر Pull Request من القائمة إذا ظهرت.',
      'اضغط Generate PR Review عندما يكون AI provider جاهزا.',
      'انسخ التقرير أو احفظه داخليا للمراجعة.',
      'نفذ أي تعليق أو merge يدويا خارج AgentFlow AI إذا قررت ذلك.',
    ],
    examples: [
      'تقرير مخاطر auth أو routes أو migrations قبل الدمج.',
      'قائمة تحقق smoke tests قبل deploy.',
    ],
    checklist: [
      'لا merge.',
      'لا comment.',
      'لا approve.',
      'لا push.',
      'لا secrets في التقرير.',
    ],
    callouts: [
      { tone: 'important', title: 'أمان', body: 'Generate PR Review ينتج تقريرا فقط. لا يغير GitHub ولا يشغل deploy.' },
    ],
    relatedLinks: [
      { label: 'Projects', href: '/dashboard/projects' },
      { label: 'Security Center', href: '/dashboard/security' },
    ],
  },
  {
    slug: 'codebase-repo-analyzer',
    title: 'دليل Codebase / Repo Analyzer',
    category: 'projects-dev',
    description: 'تحليل مستودع أو ZIP أو وصف يدوي بدون تشغيل الكود المرفوع.',
    readTime: '7 دقائق',
    difficulty: 'advanced',
    intro: 'Codebase Analyzer يقرأ الملفات النصية الآمنة ويستبعد node_modules و.env والملفات السرية. لا يشغل الكود ولا ينفذ سكربتات من ZIP.',
    steps: [
      'افتح Project ثم Codebase Analyzer إذا كان موجودا.',
      'اختر GitHub أو ZIP أو manual source.',
      'تأكد أن ZIP لا يحتوي أسرارا قبل الرفع.',
      'شغل التحليل لقراءة الملفات النصية فقط.',
      'راجع routes وAPI routes والمخاطر والتوثيق الناقص.',
      'حوّل النتائج إلى Safe Patch Plan أو مهمة مراجعة عند الحاجة.',
    ],
    examples: [
      'تحليل routes لاكتشاف صفحات dashboard غير موثقة.',
      'تحليل API routes لمراجعة auth والـ cron/webhook protection.',
    ],
    checklist: [
      'لا يتم تنفيذ الكود.',
      'ملفات .env والأسرار مستبعدة.',
      'ZIP size والنوع محدودان.',
      'النتائج لا تحتوي raw tokens.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'لا ترفع ZIP يحتوي production secrets. حتى مع التنقيح، يجب أن تبقى الأسرار خارج أدوات التحليل.' },
    ],
    relatedLinks: [
      { label: 'Projects', href: '/dashboard/projects' },
      { label: 'Safe Patch Planner', href: '/dashboard/safe-patch-planner' },
    ],
  },
  {
    slug: 'software-planner',
    title: 'دليل AI Software Project Planner',
    category: 'projects-dev',
    description: 'تحويل فكرة برنامج إلى خطة مشروع ومهام هندسية بدون تنفيذ تلقائي.',
    readTime: '6 دقائق',
    difficulty: 'intermediate',
    intro: 'Software Planner يساعدك على وصف فكرة منتج وتحويلها إلى خطة بناء، نطاق، مخاطر، ومهام مقترحة. هو تخطيط فقط.',
    steps: [
      'افتح /dashboard/software-planner.',
      'اكتب فكرة المنتج والجمهور والقيود.',
      'حدد المنصة والمخاطر والمتطلبات.',
      'ولّد الخطة إذا كان AI provider جاهزا.',
      'انسخ الخطة أو أنشئ مهام pending عند الحاجة.',
    ],
    examples: [
      'خطة SaaS داخلية مع routes وschema مبدئي وقائمة اختبارات.',
      'خطة تحسين Dashboard بدون تغيير منطق task execution.',
    ],
    checklist: [
      'الخطة لا تعدل الكود.',
      'المهام الناتجة pending فقط.',
      'لا توجد أسرار في الوصف.',
      'تمت مراجعة المخاطر قبل التنفيذ.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'استخدم Software Planner قبل Safe Patch Planner عندما تكون الفكرة كبيرة أو غير محددة.' },
    ],
    relatedLinks: [
      { label: 'Software Planner', href: '/dashboard/software-planner' },
      { label: 'Projects', href: '/dashboard/projects' },
    ],
  },
  {
    slug: 'in-app-ai-assistant',
    title: 'دليل In-App AI Assistant',
    category: 'agents-tasks',
    description: 'استخدام المساعد الداخلي للسؤال والتوجيه فقط بدون تنفيذ أفعال حساسة.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    intro: 'المساعد الداخلي يجيب على أسئلة تشغيلية من سياق آمن. لا ينشر، لا يشغل مهام، لا يغير إعدادات، ولا يكشف أسرارا.',
    steps: [
      'افتح زر المساعد داخل لوحة التحكم.',
      'اسأل سؤالا محددا عن المسار أو الخطوة التالية.',
      'استخدم إجابته كإرشاد ثم افتح الصفحة المختصة.',
      'لا تطلب منه تنفيذ نشر أو تشغيل scheduler أو تغيير providers.',
      'لا تضع secrets داخل السؤال.',
    ],
    examples: [
      'ما أول شيء أصلحه إذا كان Pinterest setup_required؟',
      'ما الفرق بين Safe Patch Planner وPR Assistant؟',
    ],
    checklist: [
      'المساعد لا ينفذ sensitive actions.',
      'الإجابة لا تحتوي أسرارا.',
      'أي إجراء حقيقي يتم من الصفحة المتخصصة.',
      'الردود لا تدعي نجاح عملية لم تحدث.',
    ],
    callouts: [
      { tone: 'important', title: 'أمان', body: 'المساعد للشرح والتوجيه فقط. لا ينشر ولا يصرف المال ولا يكتب في GitHub.' },
    ],
    relatedLinks: [
      { label: 'Dashboard', href: '/dashboard' },
      { label: 'Docs', href: '/dashboard/docs' },
    ],
  },
  {
    slug: 'safe-patch-planner',
    title: 'دليل Safe Patch Planner',
    category: 'projects-dev',
    description: 'إنشاء خطة تعديل آمنة وقابلة للنسخ إلى Codex بدون تطبيق أي patch تلقائيا.',
    readTime: '6 دقائق',
    difficulty: 'intermediate',
    intro: 'Safe Patch Planner ينتج خطة تنفيذ، نطاق، مخاطر، اختبارات، rollback، وCodex prompt. لا يكتب ملفات ولا يغير GitHub.',
    steps: [
      'افتح /dashboard/safe-patch-planner.',
      'اكتب Patch title وChange request بوضوح.',
      'حدد الأنظمة التي لا يجب لمسها.',
      'اضغط Generate Safe Patch Plan.',
      'راجع المخاطر والملفات المقترحة.',
      'استخدم Copy Codex Prompt أو Save Patch Plan عند الحاجة.',
    ],
    examples: [
      'خطة UI copy cleanup لصفحة Settings.',
      'خطة security hardening بدون تغيير webhook behavior.',
    ],
    checklist: [
      'هذه العملية planning/copy فقط.',
      'لا تعدل ملفات.',
      'لا تغير n8n/callbacks/webhooks.',
      'لا تضيف ads_management.',
      'لا تكشف أسرارا.',
    ],
    callouts: [
      { tone: 'warning', title: 'تنبيه', body: 'لا تستخدم الخطة كتفويض لتغيير مناطق no-touch. أي تعديل حساس يحتاج موافقة صريحة.' },
    ],
    relatedLinks: [
      { label: 'Safe Patch Planner', href: '/dashboard/safe-patch-planner' },
      { label: 'Projects', href: '/dashboard/projects' },
    ],
  },
  {
    slug: 'code-fix-proposal-generator',
    title: 'دليل Code Fix Proposal Generator',
    category: 'projects-dev',
    description: 'توثيق مسار مقترحات الإصلاح إذا كان مفعلا، مع حدود واضحة للتنقيح والحفظ.',
    readTime: '5 دقائق',
    difficulty: 'intermediate',
    intro: 'Code Fix Proposal Generator، إذا كان هذا المسار موجودا في التطبيق، يجب أن يولد مقترح إصلاح فقط. لا يطبق patch ولا يشغل كودا ولا يغير GitHub.',
    steps: [
      'افتح /dashboard/code-fix-proposals إذا كان هذا المسار موجودا.',
      'ألصق وصف الخطأ أو log منقحا من الأسرار.',
      'اضغط Generate Fix Proposal إذا كان الزر موجودا.',
      'راجع المقترح، المخاطر، والخطوات.',
      'انسخ prompt أو احفظ المقترح للمراجعة فقط.',
    ],
    examples: [
      'Log Sanitizer يزيل tokens وAPI keys قبل إدخالها في المقترح.',
      'مقترح إصلاح TypeScript يظل خطة حتى يطبقه مطور أو Codex بتفويض مستقل.',
    ],
    checklist: [
      'هذه العملية لا تنفذ كودا.',
      'لا توجد أسرار في logs.',
      'لا يوجد GitHub write.',
      'المقترح محفوظ كـ review/planning فقط.',
    ],
    callouts: [
      { tone: 'important', title: 'تنبيه', body: 'إذا لم يكن المسار موجودا في هذه النسخة، اعتبر الميزة غير مفعلة ولا تدّع أنها تعمل.' },
    ],
    relatedLinks: [
      { label: 'Safe Patch Planner', href: '/dashboard/safe-patch-planner' },
      { label: 'Projects', href: '/dashboard/projects' },
    ],
  },
  {
    slug: 'roles-permissions',
    title: 'دليل Roles & Permissions',
    category: 'security-admin',
    description: 'فهم owner/admin/operator/editor/viewer وحدود الوصول.',
    readTime: '6 دقائق',
    difficulty: 'intermediate',
    intro: 'Roles & Permissions تحدد من يستطيع إدارة الإعدادات، المزودين، النشر، النسخ، والأمان. إذا كانت الأدوار مفعلة، يجب حماية الإجراءات الحساسة.',
    steps: [
      'افتح Settings ثم Roles & Permissions.',
      'راجع دورك الحالي وعدد الأعضاء.',
      'افتح صفحة إدارة الأدوار إذا كنت owner.',
      'راجع permissions matrix قبل تغيير أي عضو.',
      'اختبر access denied behavior لحساب غير مخول عند الحاجة.',
    ],
    examples: [
      'viewer يقرأ التقارير فقط ولا يدير providers.',
      'operator قد يدير عمليات محتوى محددة ولا يدير الأسرار.',
    ],
    checklist: [
      'Owner فقط يدير الأدوار الحساسة.',
      'Owner/admin فقط لإعدادات المزودين والنسخ والأمان.',
      'Access denied واضح ومهني.',
      'لا توجد bypass actions في client فقط.',
    ],
    callouts: [
      { tone: 'warning', title: 'أمان', body: 'لا تعتمد على إخفاء الأزرار فقط. Server actions يجب أن تتحقق من الدور ومساحة العمل.' },
    ],
    relatedLinks: [
      { label: 'Settings', href: '/dashboard/settings' },
      { label: 'Roles', href: '/dashboard/settings/roles' },
      { label: 'Security Center', href: '/dashboard/security' },
    ],
  },
  {
    slug: 'usage-limits',
    title: 'دليل حدود الاستخدام (Usage & Quotas)',
    category: 'security-admin',
    description: 'قراءة الخطة والاستخدام وحدود الحصص التشغيلية.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    intro: 'Usage يعرض الخطة والحالة وحدود الاستخدام. هذه المنصة داخلية للفريق — لا توجد فوترة تجارية أو نظام دفع.',
    steps: [
      'افتح /dashboard/usage لعرض حدود الاستخدام والحصص.',
      'راجع plan وusage limits.',
      'راقب الاستهلاك مقابل الحصص لتجنب التوقف.',
      'إذا ظهرت setup_required، أكمل إعداد المزود في البيئة الآمنة.',
    ],
    examples: [
      'الحد الأقصى للمشاريع والمحتويات محددة حسب خطة مساحة العمل.',
      'usage limits تساعد على معرفة السقف التشغيلي.',
    ],
    checklist: [
      'لا توجد مفاتيح API أو أسرار في الواجهة.',
      'حدود الاستخدام واضحة.',
      'هذه منصة داخلية — لا توجد فوترة تجارية.',
    ],
    callouts: [
      { tone: 'important', title: 'ملاحظة', body: 'هذه المنصة داخلية للفريق. لا توجد فوترة تجارية أو نظام دفع.' },
    ],
    relatedLinks: [
      { label: 'Usage', href: '/dashboard/usage' },
      { label: 'Settings', href: '/dashboard/settings' },
    ],
  },
  {
    slug: 'analytics-reports',
    title: 'التقارير والتحليلات المتقدمة',
    category: 'best-practices',
    description: 'قراءة التقارير والتحليلات بدون تعريض الأسرار أو القيم البيئية للخطر.',
    readTime: '8 دقائق',
    difficulty: 'beginner',
    intro: 'التقارير read-only ولا تحتوي tokens أو raw provider responses.',
    steps: [
      'افتح Reports من الشريط الجانبي.',
      'اختر التقرير المطلوب: شهري، أسبوعي، أو حسب الحملة.',
      'راجع الأرقام لاتخاذ القرار التالي.',
      'استخدم System Health للتحقق من صحة الأرقام.',
      'انسخ التقرير عبر Copy Report إذا احتجت مشاركته مع الفريق.',
    ],
    examples: [
      'مثال: استعراض عدد المحتوى المنشور هذا الشهر لكل منصة.',
      'مثال: مقارنة أداء الحملات الإعلانية دون مشاركة tokens.',
    ],
    checklist: [
      'لا توجد tokens أو raw provider responses.',
      'التحليلات read-only.',
      'Copy Analytics Report لا يحتوي أسرارا.',
      'الأرقام لا تدعي بيانات غير متاحة.',
    ],
    callouts: [
      { tone: 'tip', title: 'نصيحة', body: 'استخدم التحليلات لتحديد الأولوية: setup أولا، failures ثانيا، ثم تحسين المحتوى.' },
    ],
    relatedLinks: [
      { label: 'Reports', href: '/dashboard/reports' },
      { label: 'System Health', href: '/dashboard/system-health' },
    ],
  },
  {
    slug: 'alex-guide',
    title: 'دليل Alex Assistant',
    category: 'quick-start',
    description: 'كل ما تحتاج معرفته عن Alex، المساعد الشخصي لمدير الوكالة.',
    readTime: '5 دقائق',
    difficulty: 'beginner',
    featured: true,
    intro: 'Alex هو مساعدك الشخصي لفريق الإدارة داخل AgentFlow AI. يفهم الدارجة، العربية، الفرنسية، والإنجليزية.',
    steps: [
      'افتح /dashboard/alex من الشريط الجانبي أو من أي رابط سريع.',
      'اسأل Alex عن أي شيء: المهام، المشاريع، المحتوى، المزودات، التقارير، الأمان، النسخ الاحتياطي.',
      'Alex يجيب بنفس اللغة التي تسأل بها: دارجة، عربية، فرنسية، أو إنجليزية.',
      'اطلب من Alex تحضير مسودة خطة أو ملخص، لكنه لا ينفذ الإجراءات الحساسة بدون موافقتك.',
      'استخدم الأزرار السريعة للوصول إلى الاستوديوهات والصفحات مباشرة.',
    ],
    examples: [
      'مثال: "شنو خاصني ندير اليوم؟" -> Alex يقرأ سياق مساحة العمل ويلخص الإجراءات.',
      'مثال: "وريني المشاكل ديال المزودات" -> Alex يعرض مشاكل المزودات من System Health.',
      'مثال: "حضر ليا خطة محتوى أسبوعية" -> Alex يحضر مسودة خطة ويقترح الخطوات.',
    ],
    checklist: [
      'Alex يقرأ ويلخص بيانات مساحة العمل بأمان.',
      'Alex يحضر مسودات واقتراحات فقط.',
      'Alex لا ينشر محتوى، لا يشغل المهام، لا يدفع إلى GitHub، لا يعدل المتغيرات.',
      'Alex لا يكشف الأسرار أو التوكنات.',
      'للإجراءات الحساسة، Alex يقول: "I can prepare the action and show you the steps, but I will not execute it without confirmation."',
    ],
    callouts: [
      { tone: 'important', title: 'الخصوصية', body: 'Alex لا يرسل المفاتيح أو التوكنات إلى المتصفح. كل شيء يتم عبر الخادم.' },
      { tone: 'warning', title: 'الأمان', body: 'لا تضع مفاتيح API أو أسرار داخل المحادثة.' },
    ],
    relatedLinks: [
      { label: 'Open Alex', href: '/dashboard/alex' },
      { label: 'System Health', href: '/dashboard/system-health' },
      { label: 'Provider Setup', href: '/dashboard/settings#provider-setup-wizard' },
    ],
  },
];

export function getDocBySlug(slug: string) {
  return internalDocs.find((doc) => doc.slug === slug) ?? null;
}

export function getDocCategory(categoryId: string) {
  return docCategories.find((category) => category.id === categoryId) ?? null;
}

export function getRelatedDocs(doc: InternalDoc) {
  return internalDocs
    .filter((candidate) => candidate.slug !== doc.slug && candidate.category === doc.category)
    .slice(0, 3);
}
