import type { Agent, AgentType, DepartmentName } from '@/types';

export interface AgentDisplayMetadata {
  alias: string;
  role: string;
  whenToUse: string;
  expectedOutput: string;
  helpsWith: string[];
  bestUseCases: string[];
  taskTip: string;
}

const defaultDepartmentMetadata: Record<DepartmentName, AgentDisplayMetadata> = {
  'Research & Strategy': {
    alias: 'Strategy Specialist',
    role: 'Researches direction, market context, and campaign strategy.',
    whenToUse: 'Use before creating offers, campaigns, or audience-specific content.',
    expectedOutput: 'Research notes, strategic recommendations, and next-step guidance.',
    helpsWith: ['Research', 'Positioning', 'Strategic direction'],
    bestUseCases: ['New niche research', 'Campaign planning', 'Audience clarity'],
    taskTip: 'Include the market, offer, audience, geography, and decision you need to make.',
  },
  'Content & Growth': {
    alias: 'Growth Creator',
    role: 'Turns strategy into content, copy, campaign assets, and growth ideas.',
    whenToUse: 'Use when you need marketing output ready for Content Studio or Creative Assets.',
    expectedOutput: 'Draft copy, creative direction, scripts, content ideas, and publishing-ready packages.',
    helpsWith: ['Content', 'Copy', 'Growth ideas'],
    bestUseCases: ['Campaign content', 'Captions/scripts', 'Creative briefs'],
    taskTip: 'Include the platform, objective, audience, offer, tone, CTA, and output format.',
  },
  'Sales & Operations': {
    alias: 'Operations Partner',
    role: 'Supports lead work, follow-up, customer communication, reports, and internal operations.',
    whenToUse: 'Use when the agency needs sales support, workflow organization, or reporting.',
    expectedOutput: 'Lead lists, qualification notes, outreach drafts, CRM updates, support replies, or reports.',
    helpsWith: ['Sales support', 'Operations', 'Reporting'],
    bestUseCases: ['Lead follow-up', 'Client communication', 'Monthly reporting'],
    taskTip: 'Include the source data, desired decision, follow-up rules, and report format.',
  },
  'Development & Engineering': {
    alias: 'Developer Partner',
    role: 'Plans, reviews, debugs, documents, tests, and deploys software work safely.',
    whenToUse: 'Use for software projects, GitHub/codebase reviews, build errors, database planning, UI audits, and deployment readiness.',
    expectedOutput: 'Plans, reports, checklists, risk notes, prompts, and suggested tasks. No automatic code changes.',
    helpsWith: ['Code review', 'Debugging', 'Architecture', 'Testing', 'Deployment'],
    bestUseCases: ['Project implementation planning', 'Release readiness', 'Codebase review'],
    taskTip: 'Include project context, files or errors if available, constraints, desired output, and safety limits.',
  },
};

export const agentDisplayMetadata: Partial<Record<AgentType, AgentDisplayMetadata>> = {
  market_research: {
    alias: 'Market Scout',
    role: 'Researches market opportunities, demand signals, and industry trends.',
    whenToUse: 'Use before entering a niche, launching a new service, or validating campaign direction.',
    expectedOutput: 'Market summary, trend notes, opportunity map, risks, and recommendations.',
    helpsWith: ['Market demand', 'Trend research', 'Opportunity sizing'],
    bestUseCases: ['New niche validation', 'Campaign research', 'Offer direction'],
    taskTip: 'Name the market, geography, audience, competitors, and the decision you need to make.',
  },
  competitor_analysis: {
    alias: 'Competitor Lens',
    role: 'Analyzes competitor positioning, offers, content, and strengths or weaknesses.',
    whenToUse: 'Use when you need to differentiate an offer or understand what competitors are doing.',
    expectedOutput: 'Competitor comparison, positioning gaps, content notes, and tactical recommendations.',
    helpsWith: ['Competitor research', 'Differentiation', 'Positioning gaps'],
    bestUseCases: ['Offer comparison', 'Ad angle research', 'Website/content review'],
    taskTip: 'Provide competitor names or URLs, the market, and the comparison criteria.',
  },
  audience_persona: {
    alias: 'Persona Builder',
    role: 'Builds audience personas and buyer segments for messaging and targeting.',
    whenToUse: 'Use before writing copy, scripts, ads, or sales outreach.',
    expectedOutput: 'Persona profiles, pain points, motivations, objections, and messaging hooks.',
    helpsWith: ['Audience clarity', 'Pain points', 'Messaging angles'],
    bestUseCases: ['Campaign targeting', 'Sales messaging', 'Content planning'],
    taskTip: 'Describe the product, audience clues, price point, and buying context.',
  },
  product_idea: {
    alias: 'Offer Ideator',
    role: 'Generates product, service, and package ideas based on market needs.',
    whenToUse: 'Use when shaping a new AI agency offer or improving an existing service.',
    expectedOutput: 'Offer ideas, package structure, value propositions, and validation notes.',
    helpsWith: ['Offer creation', 'Product ideas', 'Value propositions'],
    bestUseCases: ['New service package', 'Upsell ideas', 'Lead magnet ideas'],
    taskTip: 'Include current capabilities, target audience, pricing range, and constraints.',
  },
  seo_keyword: {
    alias: 'Keyword Mapper',
    role: 'Finds SEO keywords, search intent, and content opportunities.',
    whenToUse: 'Use before writing blogs, landing pages, or search-driven content.',
    expectedOutput: 'Keyword groups, search intent, content topics, and page recommendations.',
    helpsWith: ['SEO research', 'Search intent', 'Content topics'],
    bestUseCases: ['Blog planning', 'Landing page SEO', 'Keyword clustering'],
    taskTip: 'Include the niche, primary service, geography, and target reader.',
  },
  strategy_planner: {
    alias: 'Strategy Architect',
    role: 'Turns research into practical campaign, content, or agency execution plans.',
    whenToUse: 'Use when you have research and need a clear plan of action.',
    expectedOutput: 'Strategy outline, priorities, timeline, channels, and next actions.',
    helpsWith: ['Campaign planning', 'Prioritization', 'Execution roadmap'],
    bestUseCases: ['Launch plan', 'Weekly plan', 'Multi-channel campaign'],
    taskTip: 'Share the goal, timeframe, channels, resources, and success criteria.',
  },
  social_media_content: {
    alias: 'Social Publisher',
    role: 'Creates social content ideas, captions, and platform-specific post packages.',
    whenToUse: 'Use when preparing Instagram, Facebook, LinkedIn, or Pinterest content.',
    expectedOutput: 'Hooks, captions, CTAs, hashtags, and content variations.',
    helpsWith: ['Captions', 'Hooks', 'Social content'],
    bestUseCases: ['Instagram posts', 'LinkedIn authority posts', 'Weekly content ideas'],
    taskTip: 'Specify platform, audience, offer, tone, CTA, and number of variations.',
  },
  copywriting: {
    alias: 'Conversion Writer',
    role: 'Writes persuasive marketing copy for offers, pages, ads, and campaigns.',
    whenToUse: 'Use when you need stronger messaging or conversion-focused copy.',
    expectedOutput: 'Headlines, body copy, CTAs, angles, and revised copy options.',
    helpsWith: ['Sales copy', 'Headlines', 'CTAs'],
    bestUseCases: ['Landing page copy', 'Ad copy', 'Offer messaging'],
    taskTip: 'Include the offer, audience, pain point, proof, tone, and desired action.',
  },
  ads_script: {
    alias: 'Ad Scriptwriter',
    role: 'Creates short scripts and structured ad concepts for video or paid campaigns.',
    whenToUse: 'Use when planning Reels, short promos, or ad creative concepts.',
    expectedOutput: 'Hooks, scripts, scene breakdowns, on-screen text, and voiceover copy.',
    helpsWith: ['Video scripts', 'Ad concepts', 'Scene planning'],
    bestUseCases: ['Instagram Reel promo', 'Short ad script', 'UGC-style concept'],
    taskTip: 'Include length, platform, offer, audience, product proof, and visual constraints.',
  },
  email_marketing: {
    alias: 'Email Sequencer',
    role: 'Writes email campaigns, nurture sequences, and follow-up messages.',
    whenToUse: 'Use when leads or clients need structured email communication.',
    expectedOutput: 'Subject lines, email body copy, sequence flow, and CTA suggestions.',
    helpsWith: ['Email copy', 'Nurture flows', 'Follow-up'],
    bestUseCases: ['Lead nurture', 'Launch emails', 'Client onboarding emails'],
    taskTip: 'Include list segment, relationship stage, goal, offer, and sequence length.',
  },
  blog_seo_article: {
    alias: 'SEO Writer',
    role: 'Plans and drafts SEO article structures and long-form content.',
    whenToUse: 'Use when creating authority content or search-focused articles.',
    expectedOutput: 'Article outline, title options, meta description, sections, and draft copy.',
    helpsWith: ['Blog outlines', 'SEO articles', 'Authority content'],
    bestUseCases: ['Educational blog post', 'Comparison article', 'Service SEO page'],
    taskTip: 'Include target keyword, reader, intent, internal links, and desired depth.',
  },
  visual_brief: {
    alias: 'Creative Director',
    role: 'Creates visual direction, design prompts, and creative production briefs.',
    whenToUse: 'Use before generating or assigning image/video assets.',
    expectedOutput: 'Creative brief, visual style notes, asset prompts, and production guidance.',
    helpsWith: ['Creative briefs', 'Image prompts', 'Visual direction'],
    bestUseCases: ['Creative Assets prompt', 'Campaign visual style', 'Reel storyboard'],
    taskTip: 'Include platform, brand style, colors, asset format, and message hierarchy.',
  },
  lead_finder: {
    alias: 'Lead Scout',
    role: 'Identifies potential leads, segments, and prospecting targets.',
    whenToUse: 'Use when building a sales pipeline for the AI agency.',
    expectedOutput: 'Lead criteria, prospect segments, sourcing plan, and target lists when data is provided.',
    helpsWith: ['Lead sourcing', 'Prospecting', 'Target lists'],
    bestUseCases: ['Agency prospecting', 'Niche lead list', 'Outbound targeting'],
    taskTip: 'Include ideal customer profile, geography, industry, company size, and exclusions.',
  },
  lead_qualifier: {
    alias: 'Fit Checker',
    role: 'Scores and qualifies leads based on fit, urgency, budget, and need.',
    whenToUse: 'Use after collecting leads or receiving inquiries.',
    expectedOutput: 'Qualification score, reasons, objections, and recommended next step.',
    helpsWith: ['Lead scoring', 'Qualification', 'Prioritization'],
    bestUseCases: ['CRM review', 'Inbound lead triage', 'Outbound list cleanup'],
    taskTip: 'Provide lead details, qualification criteria, and what counts as a good fit.',
  },
  outreach_message: {
    alias: 'Outreach Writer',
    role: 'Writes personalized outreach messages for leads and prospects.',
    whenToUse: 'Use when contacting prospects, following up, or testing outbound angles.',
    expectedOutput: 'DM/email variants, personalization hooks, follow-up copy, and CTA options.',
    helpsWith: ['Outbound messages', 'Personalization', 'Follow-up'],
    bestUseCases: ['Cold email', 'LinkedIn DM', 'Follow-up sequence'],
    taskTip: 'Include lead context, offer, channel, tone, and what you want them to do next.',
  },
  crm_update: {
    alias: 'CRM Organizer',
    role: 'Organizes lead and client notes into clear CRM-ready updates.',
    whenToUse: 'Use when you need clean operational notes after calls, messages, or pipeline changes.',
    expectedOutput: 'CRM summary, stage recommendation, next task, and follow-up notes.',
    helpsWith: ['CRM notes', 'Pipeline hygiene', 'Follow-up tasks'],
    bestUseCases: ['Call summary', 'Pipeline update', 'Client status note'],
    taskTip: 'Paste the raw notes and specify the CRM fields or stage options.',
  },
  customer_support: {
    alias: 'Support Responder',
    role: 'Drafts helpful client replies, support answers, and issue summaries.',
    whenToUse: 'Use when responding to client questions or turning issues into clear next steps.',
    expectedOutput: 'Support response, summary, tone-adjusted reply, and escalation guidance.',
    helpsWith: ['Client replies', 'Support summaries', 'Issue handling'],
    bestUseCases: ['Client question', 'Bug explanation', 'Service update response'],
    taskTip: 'Include the client message, context, desired tone, and what can/cannot be promised.',
  },
  analytics_report: {
    alias: 'Report Builder',
    role: 'Summarizes performance, workflow activity, and operational progress.',
    whenToUse: 'Use at the end of a week/month or after campaign activity.',
    expectedOutput: 'Report summary, metrics interpretation, blockers, wins, and next actions.',
    helpsWith: ['Reports', 'Performance summary', 'Next actions'],
    bestUseCases: ['Monthly report', 'Campaign recap', 'Operations review'],
    taskTip: 'Provide the date range, metrics, campaign context, and audience for the report.',
  },
  'code-review-agent': {
    alias: 'Reviewer',
    role: 'Reviews code quality, structure, readability, maintainability, and potential bugs.',
    whenToUse: 'Use after code changes, before a release, or when reviewing a pull request summary.',
    expectedOutput: 'Code review report with findings, severity, recommended fixes, and testing checklist.',
    helpsWith: ['Changed-file review', 'PR review', 'Risk detection', 'Refactor suggestions'],
    bestUseCases: ['Review changed files', 'Inspect component structure', 'Identify risky code'],
    taskTip: 'Include changed files, PR summary, code snippets, route/context, and the level of strictness needed.',
  },
  'bug-fix-agent': {
    alias: 'Debugger',
    role: 'Analyzes errors, logs, screenshots, and failing behavior to propose a safe fix plan.',
    whenToUse: 'Use when builds fail, routes crash, UI breaks, API calls fail, or TypeScript errors appear.',
    expectedOutput: 'Root cause hypothesis, files to inspect, fix plan, test steps, and a safe Codex prompt.',
    helpsWith: ['Build errors', 'Runtime crashes', 'TypeScript errors', 'Broken UI behavior'],
    bestUseCases: ['Triage build error', 'Plan runtime bug fix', 'Investigate failed API call'],
    taskTip: 'Paste exact error messages, affected route, recent change, expected behavior, and screenshots/logs when safe.',
  },
  'architecture-agent': {
    alias: 'System Architect',
    role: 'Plans system architecture, project structure, data flow, and implementation phases.',
    whenToUse: 'Use before building a new feature, integrating providers, or restructuring a software project.',
    expectedOutput: 'Architecture plan, folder structure, data model, API/server actions plan, risks, and tradeoffs.',
    helpsWith: ['SaaS planning', 'Feature architecture', 'Data flow', 'Module organization'],
    bestUseCases: ['New SaaS project plan', 'Provider integration design', 'Feature phase plan'],
    taskTip: 'Include goals, users, current stack, constraints, integrations, data needs, and non-goals.',
  },
  'testing-agent': {
    alias: 'QA Planner',
    role: 'Creates testing checklists and QA plans for software releases.',
    whenToUse: 'Use before release, after bug fixes, or when stabilizing routes, forms, providers, and dashboards.',
    expectedOutput: 'Manual test checklist, automated test suggestions, edge cases, and acceptance criteria.',
    helpsWith: ['Smoke testing', 'Route QA', 'Provider readiness tests', 'Regression checklist'],
    bestUseCases: ['Final stabilization', 'Form validation plan', 'Deployment verification'],
    taskTip: 'Include changed features, routes, risk areas, provider dependencies, and target devices.',
  },
  'documentation-agent': {
    alias: 'Technical Writer',
    role: 'Creates internal guides, user docs, technical reports, release notes, FAQs, and checklists.',
    whenToUse: 'Use when a feature needs internal docs, onboarding notes, release summaries, or setup guides.',
    expectedOutput: 'Structured Arabic/English documentation, changelog, FAQ, guide, or checklist.',
    helpsWith: ['Docs Center articles', 'Release summaries', 'Setup guides', 'Project reports'],
    bestUseCases: ['Write feature guide', 'Create release notes', 'Document provider setup'],
    taskTip: 'Include audience, route/feature, current behavior, screenshots or facts, and preferred language.',
  },
  'deployment-agent': {
    alias: 'Release Operator',
    role: 'Prepares deployment plans, Vercel checks, env checklist, smoke tests, and rollback notes.',
    whenToUse: 'Use before production deploys, after build errors, or when migrations/settings must be checked.',
    expectedOutput: 'Deploy prompt, env checklist, migration checklist, smoke test report, and rollback plan.',
    helpsWith: ['Vercel deploy', 'Migration checks', 'Build errors', 'Rollback plan'],
    bestUseCases: ['Production deployment', 'Vercel CLI issue', 'Post-deploy smoke test'],
    taskTip: 'Include build/lint/typecheck output, routes changed, migrations, env names only, and rollback constraints.',
  },
  'security-review-agent': {
    alias: 'Security Auditor',
    role: 'Reviews security risks, secret exposure, RLS, uploads, OAuth, and token storage.',
    whenToUse: 'Use before releasing integrations, uploads, auth changes, API routes, or provider/token work.',
    expectedOutput: 'Security review report, risks, recommended fixes, and no-secrets checklist.',
    helpsWith: ['Secret exposure', 'RLS review', 'OAuth/token storage', 'Upload safety'],
    bestUseCases: ['Env safety review', 'RLS audit', 'File upload security review'],
    taskTip: 'Include affected routes/tables, auth model, storage behavior, and confirm no secret values are pasted.',
  },
  'database-agent': {
    alias: 'Supabase Planner',
    role: 'Plans and reviews database schema, Supabase migrations, RLS, indexes, relationships, and storage policies.',
    whenToUse: 'Use before adding tables, applying migrations, or designing workspace-scoped data.',
    expectedOutput: 'Migration plan, SQL review, RLS checklist, relationship notes, and Supabase testing steps.',
    helpsWith: ['Table design', 'Migration review', 'RLS policies', 'Indexes', 'Storage policies'],
    bestUseCases: ['New table design', 'Workspace-scoped schema', 'Supabase migration review'],
    taskTip: 'Include table purpose, fields, relationships, workspace ownership, access rules, and migration constraints.',
  },
  'ui-ux-review-agent': {
    alias: 'Interface Reviewer',
    role: 'Reviews UI layout, spacing, readability, cards, forms, flows, accessibility, and responsiveness.',
    whenToUse: 'Use when dashboards feel cluttered, mobile layouts need review, or forms/cards need polish.',
    expectedOutput: 'UI/UX audit, design improvements, layout fixes, accessibility notes, and responsive checklist.',
    helpsWith: ['Dashboard layout', 'Form UX', 'Readability', 'Mobile responsiveness'],
    bestUseCases: ['Reports design review', 'Content Studio organization', 'Mobile layout audit'],
    taskTip: 'Include route, screenshots if safe, target user, workflow goal, and known layout problems.',
  },
};

export function getAgentDisplayMetadata(agent: Agent): AgentDisplayMetadata {
  return agentDisplayMetadata[agent.id] ?? defaultDepartmentMetadata[agent.department];
}

export function getDepartmentUsageSummary(department: DepartmentName) {
  const metadata = defaultDepartmentMetadata[department];

  return {
    title: department,
    description: metadata.whenToUse,
    examples: metadata.bestUseCases,
  };
}
